import type { Lang } from '@/lib/i18n'
import { articleContentEN } from '@/lib/article-content'

export interface BlogChromeDict {
  eyebrow: string
  h1pre: string
  h1em: string
  sub: string
  backToBlog: string
  ctaTitle: string
  ctaSub: string
  ctaShop: string
  ctaQuiz: string
  more: string
}

export const blogChrome: Record<Lang, BlogChromeDict> = {
  en: {
    eyebrow: `bloom focus blog`, h1pre: `Understanding your `, h1em: `ADHD brain`,
    sub: `No jargon, no shame, no "just try harder." Real information about how neurodivergent brains work — and what actually helps.`,
    backToBlog: `← Back to blog`, ctaTitle: `Ready to try tools that actually work?`,
    ctaSub: `Browse the bloom focus toolkit — designed for ADHD brains, built with care.`,
    ctaShop: `Shop the toolkit ✨`, ctaQuiz: `Take the free ADHD test 🧠`, more: `More from the blog`,
  },
  de: {
    eyebrow: `bloom focus Blog`, h1pre: `Verstehe dein `, h1em: `ADHS-Gehirn`,
    sub: `Kein Fachjargon, keine Scham, kein „streng dich einfach mehr an". Echte Informationen darüber, wie neurodivergente Gehirne funktionieren – und was wirklich hilft.`,
    backToBlog: `← Zurück zum Blog`, ctaTitle: `Bereit für Werkzeuge, die wirklich funktionieren?`,
    ctaSub: `Entdecke das bloom focus Toolkit – für ADHS-Köpfe gestaltet, mit Sorgfalt gemacht.`,
    ctaShop: `Zum Toolkit ✨`, ctaQuiz: `Kostenlosen ADHS-Test machen 🧠`, more: `Mehr aus dem Blog`,
  },
  fr: {
    eyebrow: `blog bloom focus`, h1pre: `Comprendre ton `, h1em: `cerveau TDAH`,
    sub: `Pas de jargon, pas de honte, pas de « fais juste plus d'efforts ». De vraies informations sur le fonctionnement des cerveaux neurodivergents – et ce qui aide vraiment.`,
    backToBlog: `← Retour au blog`, ctaTitle: `Prêt·e à essayer des outils qui marchent vraiment ?`,
    ctaSub: `Découvre la boîte à outils bloom focus – pensée pour les cerveaux TDAH, conçue avec soin.`,
    ctaShop: `Découvrir les outils ✨`, ctaQuiz: `Faire le test TDAH gratuit 🧠`, more: `Plus d'articles du blog`,
  },
  es: {
    eyebrow: `blog bloom focus`, h1pre: `Entender tu `, h1em: `cerebro con TDAH`,
    sub: `Sin jerga, sin culpa, sin «solo esfuérzate más». Información real sobre cómo funcionan los cerebros neurodivergentes, y qué ayuda de verdad.`,
    backToBlog: `← Volver al blog`, ctaTitle: `¿Listo·a para probar herramientas que de verdad funcionan?`,
    ctaSub: `Explora el kit bloom focus: diseñado para cerebros con TDAH, hecho con cariño.`,
    ctaShop: `Ver las herramientas ✨`, ctaQuiz: `Hacer el test TDAH gratis 🧠`, more: `Más del blog`,
  },
}

// English blog tag -> localized
export const blogTagMap: Record<Lang, Record<string, string>> = {
  en: {},
  de: { 'Understanding ADHD': `ADHS verstehen`, 'Tools & Tips': `Tools & Tipps` },
  fr: { 'Understanding ADHD': `Comprendre le TDAH`, 'Tools & Tips': `Outils & astuces` },
  es: { 'Understanding ADHD': `Entender el TDAH`, 'Tools & Tips': `Herramientas y consejos` },
}

// Localized title + excerpt per slug (en comes from lib/articles).
export const articleMeta: Record<string, Partial<Record<Lang, { title: string; excerpt: string }>>> = {
  'adhd-rejection-sensitive-dysphoria': {
    de: { title: `ADHS und Rejection Sensitive Dysphoria: Warum Kritik so weh tut`, excerpt: `Wenn eine kleine Kritik deinen ganzen Tag ruinieren kann, bist du nicht zu empfindlich – vielleicht erlebst du RSD, einen der schmerzhaftesten und am wenigsten bekannten Teile von ADHS.` },
  },
  'adhd-and-sleep': {
    de: { title: `ADHS und Schlaf: Warum dein Gehirn nachts nicht abschaltet`, excerpt: `Gedankenkarussell um Mitternacht, ein zweiter Wind genau dann, wenn du schlafen solltest, Morgen, die unmöglich scheinen – ADHS und Schlafprobleme gehören zusammen. Hier ist, warum, und was hilft.` },
  },
  'body-doubling-adhd': {
    de: { title: `Body Doubling: Der ADHS-Fokus-Trick, der wirklich funktioniert`, excerpt: `Warum fällt das Arbeiten so viel leichter, wenn jemand anderes im Raum ist? Body Doubling macht daraus eine Strategie – eines der zuverlässigsten ADHS-Fokus-Werkzeuge überhaupt.` },
  },
  'adhd-burnout': {
    de: { title: `ADHS-Burnout: Die Anzeichen, dass du auf dem Zahnfleisch gehst (und wie du dich erholst)`, excerpt: `ADHS-Burnout ist keine gewöhnliche Müdigkeit – es ist der Zusammenbruch nach Monaten des Maskierens und Überkompensierens. Hier ist, wie du es erkennst und sanft genesen kannst.` },
  },
  'how-to-clean-with-adhd': {
    de: { title: `Wie du mit ADHS dein Zuhause putzt – ohne Überforderung`, excerpt: `Wenn Putzen unmöglich scheint, bis es zur Krise wird, bist du nicht faul – dein Gehirn braucht nur einen anderen Ansatz. So putzt du mit einem ADHS-Gehirn, Schritt für sanften Schritt.` },
  },
  'why-adhd-brains-struggle-with-planning': {
    de: { title: `Warum ADHS-Gehirne mit Planung kämpfen (und was wirklich hilft)`, excerpt: `Planung fühlt sich unmöglich an – nicht weil du faul bist, sondern weil dein Gehirn anders verdrahtet ist. Hier ist die Wissenschaft dahinter und was du tun kannst.` },
    fr: { title: `Pourquoi les cerveaux TDAH peinent à planifier (et ce qui aide vraiment)`, excerpt: `Planifier semble impossible – non parce que tu es paresseux·se, mais parce que ton cerveau est câblé différemment. Voici la science, et ce que tu peux y faire.` },
    es: { title: `Por qué a los cerebros con TDAH les cuesta planificar (y qué ayuda de verdad)`, excerpt: `Planificar parece imposible, no porque seas perezoso·a, sino porque tu cerebro está cableado de otra forma. Aquí tienes la ciencia y qué puedes hacer.` },
  },
  'dopamine-menu-guide': {
    de: { title: `Was ist ein Dopamin-Menü und wie erstellst du eines, das funktioniert`, excerpt: `Ein Dopamin-Menü ist eines der wirksamsten ADHS-Werkzeuge – und überraschend einfach. So baust du deins.` },
    fr: { title: `Qu'est-ce qu'un menu dopamine et comment en créer un qui marche`, excerpt: `Le menu dopamine est l'un des outils TDAH les plus efficaces – et étonnamment simple. Voici comment créer le tien.` },
    es: { title: `Qué es un menú de dopamina y cómo crear uno que funcione`, excerpt: `Un menú de dopamina es una de las herramientas TDAH más eficaces, y sorprendentemente simple. Así creas el tuyo.` },
  },
  'time-blindness-adhd': {
    de: { title: `Zeitblindheit: Warum du das Vergehen der Zeit nicht spürst (und was hilft)`, excerpt: `Zeitblindheit ist eines der am meisten missverstandenen ADHS-Symptome. Es geht nicht um Verantwortungslosigkeit – es ist neurologisch.` },
    fr: { title: `Cécité temporelle : pourquoi tu ne sens pas le temps passer (et ce qui aide)`, excerpt: `La cécité temporelle est l'un des symptômes du TDAH les plus mal compris. Ce n'est pas de l'irresponsabilité – c'est neurologique.` },
    es: { title: `Ceguera temporal: por qué no sientes pasar el tiempo (y qué ayuda)`, excerpt: `La ceguera temporal es uno de los síntomas del TDAH más malinterpretados. No es irresponsabilidad: es neurológico.` },
  },
  'habit-stacking-adhd': {
    de: { title: `Habit Stacking bei ADHS: Routinen aufbauen, die wirklich bleiben`, excerpt: `Die meisten Gewohnheits-Tipps versagen bei ADHS-Köpfen. Hier ist ein sanfterer Ansatz, der mit deinem Gehirn arbeitet.` },
    fr: { title: `Habit stacking et TDAH : construire des routines qui tiennent vraiment`, excerpt: `La plupart des conseils sur les habitudes échouent avec les cerveaux TDAH. Voici une approche plus douce, adaptée à ton fonctionnement.` },
    es: { title: `Habit stacking y TDAH: crear rutinas que de verdad se quedan`, excerpt: `La mayoría de los consejos sobre hábitos fallan con los cerebros con TDAH. Aquí tienes un enfoque más suave, hecho a tu medida.` },
  },
  'do-i-have-adhd-test': {
    de: { title: `Hast du ADHS? Wie du es erkennst – und was du als Nächstes tust`, excerpt: `Fragst du dich, ob du ADHS hast? Hier sind die Anzeichen, die Erwachsene wirklich erleben, wie sich unaufmerksamer und hyperaktiver Typ unterscheiden, und die nächsten Schritte.` },
    fr: { title: `As-tu un TDAH ? Comment le savoir – et que faire ensuite`, excerpt: `Tu te demandes si tu as un TDAH ? Voici les signes que vivent vraiment les adultes, en quoi les types inattentif et hyperactif diffèrent, et les étapes à suivre.` },
    es: { title: `¿Tienes TDAH? Cómo saberlo y qué hacer después`, excerpt: `¿Te preguntas si tienes TDAH? Aquí están las señales que viven de verdad los adultos, en qué se diferencian el tipo inatento y el hiperactivo, y los pasos a seguir.` },
  },
  'adhd-paralysis': {
    de: { title: `ADHS-Paralyse: Warum du erstarrst – und wie du wieder ins Tun kommst`, excerpt: `Du weißt genau, was zu tun ist, du willst es tun, und kommst trotzdem nicht von der Stelle. Das ist ADHS-Paralyse. Hier ist, warum sie passiert, und sanfte Wege heraus.` },
    fr: { title: `Paralysie TDAH : pourquoi tu te figes – et comment te débloquer`, excerpt: `Tu sais exactement quoi faire, tu veux le faire, et tu n'arrives toujours pas à bouger. C'est la paralysie TDAH. Voici pourquoi elle arrive et des façons douces de briser le gel.` },
    es: { title: `Parálisis por TDAH: por qué te bloqueas y cómo desatascarte`, excerpt: `Sabes exactamente qué hacer, quieres hacerlo y aun así no logras moverte. Eso es la parálisis por TDAH. Aquí está por qué ocurre y formas suaves de romper el bloqueo.` },
  },
  'best-planner-for-adhd': {
    de: { title: `Der beste Planer für ADHS (und warum die meisten Planer dich im Stich lassen)`, excerpt: `Die meisten Planer sind für neurotypische Gehirne gemacht – deshalb verstauben sie ab Woche zwei. Das sollte ein ADHS-freundlicher Planer wirklich können.` },
    fr: { title: `Le meilleur agenda pour le TDAH (et pourquoi la plupart te laissent tomber)`, excerpt: `La plupart des agendas sont pensés pour les cerveaux neurotypiques – d'où la poussière dès la deuxième semaine. Voici ce qu'un agenda adapté au TDAH doit vraiment avoir.` },
    es: { title: `La mejor agenda para el TDAH (y por qué la mayoría te fallan)`, excerpt: `La mayoría de las agendas están hechas para cerebros neurotípicos, por eso acumulan polvo en la segunda semana. Esto es lo que una agenda apta para el TDAH necesita de verdad.` },
  },
  'adhd-in-women': {
    de: { title: `ADHS bei Frauen: Die Anzeichen, die jahrelang übersehen werden`, excerpt: `ADHS bei Frauen wird chronisch unterdiagnostiziert, weil es oft wie Angst, Perfektionismus oder einfach „Zerstreutheit" aussieht. Hier sind die übersehenen Anzeichen.` },
    fr: { title: `Le TDAH chez les femmes : les signes que l'on rate pendant des années`, excerpt: `Le TDAH chez les femmes est chroniquement sous-diagnostiqué car il ressemble souvent à de l'anxiété, du perfectionnisme ou à de la « tête en l'air ». Voici les signes que l'on néglige.` },
    es: { title: `TDAH en mujeres: las señales que se pasan por alto durante años`, excerpt: `El TDAH en mujeres está crónicamente infradiagnosticado porque a menudo parece ansiedad, perfeccionismo o simplemente ser «despistada». Aquí están las señales que se pasan por alto.` },
  },
}

// Localized article bodies (paragraph arrays) per slug. Filled in language by
// language; any slug/lang not present here falls back to the English body.
export const articleBody: Record<string, Partial<Record<Lang, string[]>>> = {
  'adhd-rejection-sensitive-dysphoria': {
    de: [
      `Rejection Sensitive Dysphoria, kurz RSD, ist der intensive emotionale Schmerz, der auf echte oder vermeintliche Ablehnung, Kritik oder Misserfolg folgt. Für viele Menschen mit ADHS ist es das störendste Symptom von allen, und doch wird fast niemand bei der Diagnose davor gewarnt. Eine beiläufige Bemerkung einer Kollegin, eine Nachricht, die unbeantwortet bleibt, oder ein winziger Fehler bei der Arbeit kann jeweils eine Welle von Schmerz auslösen, die sich körperlich anfühlt und in keinem Verhältnis zu dem steht, was tatsächlich passiert ist.`,
      `Der Grund ist neurologisch, keine Frage von Dünnhäutigkeit. ADHS-Gehirne regulieren Emotionen anders, und Gefühle kommen tendenziell schneller, lauter und schwerer abschaltbar. Dieselben Dopamin- und Noradrenalin-Systeme, die das Fokussieren erschweren, machen auch die emotionale Intensität schwerer herunterzuregeln – wo eine neurotypische Person einen kleinen Stich spürt, kann ein ADHS-Gehirn innerhalb von Sekunden etwas erleben, das echter Verzweiflung näherkommt.`,
      `RSD trägt viele verschiedene Verkleidungen. Manchmal sieht es aus wie People-Pleasing, bei dem du zu allem Ja sagst, damit niemand je von dir enttäuscht ist. Manchmal sieht es aus wie Perfektionismus oder das stille Vermeiden von Dingen, bei denen du scheitern könntest. Manchmal kippt es nach außen in plötzliche Wut oder Abwehr. Und sehr oft sieht es aus wie Rückzug: Pläne absagen, Feedback meiden oder dich von Menschen zurückziehen, sobald du spürst, dass du beurteilt werden könntest.`,
      `Weil der Schmerz unsichtbar ist, wird Menschen mit RSD oft gesagt, sie würden überreagieren oder seien dramatisch. Diese Reaktion macht alles schlimmer, weil sie Scham auf ein ohnehin überwältigendes Gefühl stapelt. Zu verstehen, dass RSD ein anerkanntes Muster innerhalb von ADHS ist und kein Charakterfehler, ist oft das Erleichterndste, was ein Mensch lernen kann, weil es endlich ein Leben voller Reaktionen erklärt, die nie Sinn zu ergeben schienen.`,
      `Was hilft, ist eine Mischung aus Benennen und Distanz. Den Moment als „das ist RSD, nicht die Wahrheit" zu erkennen, schafft einen kleinen Abstand zwischen dem Gefühl und deiner Reaktion darauf. Zu warten, bevor du auf eine auslösende Nachricht antwortest, deine Deutung an den tatsächlichen Fakten zu prüfen und dir sanfte Skripte für das Annehmen von Feedback vorzubereiten, senken alle die Intensität. Genauso hilft offenes Reden mit Menschen, denen du vertraust und die dich daran erinnern, dass ein Kommentar kein Urteil über deinen Wert ist.`,
      `Vor allem reagiert RSD auf Selbstmitgefühl statt auf Selbstkritik. Das Gefühl ist real und es ist schmerzhaft, aber es ist auch vorübergehend, und es geht schneller vorbei, wenn du ihm mit Freundlichkeit begegnest, statt es zu bekämpfen. Du bist nicht zu viel, und du bist nicht kaputt. Du hast einfach ein Gehirn, das Dinge in voller Lautstärke fühlt – und dieselbe Intensität, in eine andere Richtung gelenkt, ist oft auch dort, wo deine Wärme und Kreativität herkommen.`,
    ],
  },
  'adhd-and-sleep': {
    de: [
      `Wenn dein Gehirn in dem Moment lebendig wird, in dem dein Kopf das Kissen berührt, bist du alles andere als allein. Schlafprobleme gehören zu den häufigsten und am wenigsten besprochenen Seiten von ADHS und betreffen eine große Mehrheit der Erwachsenen mit dieser Diagnose. Das Muster ist schmerzhaft vertraut: den ganzen Tag erschöpft, dann plötzlich nachts hellwach, mit einem Kopf, der durch Gespräche, Ideen, Sorgen und die To-do-Liste von morgen rast – genau dann, wenn du ihn am dringendsten still bräuchtest.`,
      `Ein Teil davon ist schlicht biologisch. Viele Menschen mit ADHS haben einen verschobenen zirkadianen Rhythmus, was bedeutet, dass ihr natürliches Schlafsignal ein paar Stunden später eintrifft, als der Rest der Welt es erwartet. Hinzu kommt, dass das ADHS-Gehirn unterstimuliert ist, wenn es nichts zu tun gibt, sodass sich die Stille der Schlafenszeit eher unerträglich als erholsam anfühlt und der Geist nach Stimulation sucht – in Form von rasenden Gedanken oder noch einer Folge.`,
      `Hier kommt der berüchtigte zweite Wind ins Spiel. Gerade wenn dein Körper endlich bereit ist herunterzufahren, taucht ein Energie- oder Fokusschub auf, und plötzlich putzt du um Mitternacht gründlich die Küche oder beginnst ein Projekt. Forschende nennen das weitere Muster manchmal Revenge Bedtime Procrastination: Wenn der Tag dir keine Zeit gelassen hat, die sich nach dir anfühlt, wird die späte Nacht zum einzigen Fenster für Freiheit – und der Schlaf verliert leise.`,
      `Die Morgen zahlen dann den Preis. ADHS-Gehirne erleben oft eine intensive Schlafträgheit, jenen schweren, nebligen Zustand, der das Aufstehen fast unmöglich macht, egal wie viele Wecker gestellt sind. Das ist keine Faulheit und kein moralisches Versagen. Es ist das vorhersehbare Ergebnis eines Gehirns, das viel zu spät eingeschlafen ist und nun auf einem Zeitplan aufwachen soll, der für die innere Uhr von jemand anderem gemacht wurde.`,
      `Was hilft, ist sanft und beständig statt streng. Eine Einschlafroutine, die früher beginnt, als nötig scheint, ein Brain Dump auf Papier, um die rasenden Gedanken vor dem Schlafen zu leeren, gedämpftes Licht am Abend und helles Licht am Morgen sowie eine Aufstehzeit, die auch am Wochenende ungefähr gleich bleibt, schieben den Rhythmus alle zurück an seinen Platz. Die Aufgaben von morgen zu externalisieren, damit dein Gehirn darauf vertraut, dass sie sicher festgehalten sind, ist oft der Unterschied zwischen Wachliegen und Loslassen.`,
      `Sei geduldig mit dir, während du experimentierst, denn Schlaf wird selten in einer einzigen Nacht repariert. Das Ziel ist keine perfekte Lehrbuch-Schlafhygiene; es ist eine Handvoll kleiner, wiederholbarer Gewohnheiten, die das Einschlafen ein wenig leichter und die Morgen ein wenig freundlicher machen. Mit deiner inneren Uhr zu arbeiten statt gegen sie ist weit nachhaltiger, als einen Zeitplan zu erzwingen, der nie für ein ADHS-Gehirn gebaut wurde.`,
    ],
  },
  'body-doubling-adhd': {
    de: [
      `Ist dir schon aufgefallen, wie viel leichter dir Dinge von der Hand gehen, wenn einfach jemand anderes im Raum ist? Genau das ist die Idee hinter Body Doubling, einer der zuverlässigsten Fokus-Strategien für ADHS-Gehirne. Ein Body Double ist eine Person, die neben dir arbeitet – nicht bei deiner Aufgabe hilft, sondern nur anwesend ist – und deren ruhige Gegenwart die unmögliche Aufgabe irgendwie plötzlich machbar macht.`,
      `Es funktioniert, weil ADHS im Kern eine Herausforderung der Selbstregulation ist und nicht des Wissens. Meist weißt du genau, was zu tun ist; das Schwierige ist das Anfangen und Dranbleiben. Eine andere Person dort zu haben, schafft sanfte äußere Verbindlichkeit und ein geliehenes Gefühl von Fokus, und es fügt gerade genug Neuheit und milde soziale Präsenz hinzu, um deinem Gehirn den Dopamin-Schubs zu geben, den es zum Beginnen und Weitermachen braucht.`,
      `Body Doubling gibt es in vielen Formen, du kannst also wählen, was zu deinem Leben passt. Es kann eine Freundin sein, die auf dem Sofa liest, während du Papierkram sortierst, ein Partner, der kocht, während du aufräumst, oder ein Videoanruf, bei dem zwei Menschen in Stille an völlig getrennten Dingen arbeiten. Es gibt auch eigene virtuelle Coworking-Plattformen und ADHS-freundliche Fokus-Apps, bei denen du dich einer Sitzung mit Fremden anschließt und einfach parallel arbeitest.`,
      `Die Einrichtung ist erfrischend einfach. Entscheide, woran du arbeiten wirst, sag deinem Body Double, was du beginnst, einigt euch auf eine Zeitspanne und fangt dann gemeinsam an. Ein kurzer Check-in am Ende, bei dem ihr benennt, was jede und jeder geschafft hat, schließt den Kreis und beschert ein kleines Gefühl von Zufriedenheit. Entscheidend ist, dass dich niemand beaufsichtigt oder bewertet; der Zauber liegt rein in der geteilten Anwesenheit.`,
      `Body Doubling glänzt genau bei den Aufgaben, die ADHS-Gehirne am meisten meiden: langweiliger Papierkram, Putzen, E-Mail-Rückstände, Formulare ausfüllen und alles, was seit Wochen unangetastet liegt. Es geht weniger um die Fähigkeiten der anderen Person und mehr darum, den Bann des Vermeidens zu brechen – deshalb kann selbst ein nahezu stiller Begleiter, der nichts von deiner Arbeit versteht, völlig verändern, was du zu erledigen schaffst.`,
      `Wenn du immer schon besser in einem belebten Café gearbeitet oder dich seltsam produktiv gefühlt hast, wenn eine Freundin in der Nähe war, dann macht Body Doubling aus diesem Instinkt einfach ein Werkzeug, nach dem du bewusst greifen kannst. Es ist keine Krücke und kein Schummeln. Es ist eine kluge Anpassung, die mit der Verdrahtung deines Gehirns arbeitet, und viele erleben es als eine ihrer verlässlichsten Arten, anzufangen.`,
    ],
  },
  'adhd-burnout': {
    de: [
      `ADHS-Burnout ist nicht dasselbe wie gewöhnliche Müdigkeit, und es ist nicht dasselbe wie alltäglicher Stress. Es ist die tiefe, den ganzen Körper erfassende Erschöpfung, die nach Monaten oder Jahren kommt, in denen ein Gehirn gezwungen wurde, auf Arten zu funktionieren, für die es nie gebaut war. Oft folgt es auf eine lange Phase des Maskierens, Überkompensierens und Sich-durch-den-Alltag-Beißens, bis eines Tages die Systeme, die kaum noch hielten, schließlich alle auf einmal versagen.`,
      `ADHS-Gehirne sind besonders anfällig dafür, weil so viel unsichtbare Anstrengung darin steckt, in Ordnung zu wirken. Erinnern, Planen, Impulse unterdrücken, Emotionen steuern und neurotypische Erwartungen erfüllen kosten alle exekutive Energie, die ohnehin knapp ist. In einem ständigen Zustand des Aufholens zu leben, erzeugt eine Art chronischen exekutiven Überziehungskredit, und irgendwann wird die Rechnung in Form von Burnout fällig.`,
      `Die Anzeichen werden leicht für etwas anderes gehalten. Aufgaben, die einst machbar waren, beginnen sich unmöglich anzufühlen, die Motivation verschwindet völlig, und selbst kleine Entscheidungen werden überwältigend. Du fühlst dich vielleicht emotional flach oder ungewöhnlich nah am Wasser gebaut, wirst öfter krank, ziehst dich von den Menschen um dich herum zurück und bemerkst, wie deine ADHS-Symptome – von Vergesslichkeit über Zeitblindheit bis Ablenkbarkeit – dramatisch schlimmer werden als sonst.`,
      `Was ADHS-Burnout so grausam macht, ist die Scham, die danebenherläuft. Viele deuten den Zusammenbruch als Beweis, dass sie faul sind oder versagen, und versuchen dann, sich mit genau der Anstrengung hindurchzuzwingen, die ihn überhaupt verursacht hat. Diese Reaktion vertieft das Loch nur, denn Burnout löst man nicht durch mehr Anstrengung; man löst es, indem man für eine Weile wirklich – und oft unbequem – weniger tut.`,
      `Erholung beginnt mit der Erlaubnis, zu ruhen, ohne es sich zu verdienen. Die Messlatte bewusst niedriger zu legen, jede nicht zwingende Verpflichtung fallenzulassen, Aufgaben zu externalisieren, damit dein Gehirn aufhören kann, sie zu halten, und um Unterstützung zu bitten, sind keine Nachgiebigkeiten; sie sind die eigentliche Behandlung. Es hilft auch, ehrlich anzuschauen, was hierher geführt hat, denn Burnout ist häufig ein Zeichen, dass dein Leben mehr von deiner exekutiven Funktion verlangt, als irgendein Gehirn nachhaltig geben kann.`,
      `Von ADHS-Burnout zu heilen geht selten schnell, und es kommt eher in Wellen als in einer geraden Linie. Sei geduldig und sanft mit dir, schütze deine Energie, als ob sie zählt – denn das tut sie wirklich –, und baue deine Routinen langsam wieder auf, mit weit mehr Raum für Ruhe, als vernünftig scheint. Das Ziel ist nicht, zurück zum Laufen auf Reserve zu kommen; es ist, ein Leben zu bauen, das den Tank gar nicht erst leert.`,
    ],
  },
  'how-to-clean-with-adhd': {
    de: [
      `Wenn dein Zuhause zwischen makellos und totalem Chaos pendelt, mit sehr wenig dazwischen, bist du nicht faul und kein Schlamper. Putzen ist für ADHS-Gehirne wirklich schwerer, weil es genau auf den Fähigkeiten sitzt, die ADHS erschwert: anfangen, in eine Reihenfolge bringen, die Aufmerksamkeit halten und sich von einer Aufgabe motivieren lassen, die keine Neuheit und sehr wenig Belohnung bietet, bis sie vollständig fertig ist.`,
      `Ein großer Teil des Kampfes ist das Alles-oder-nichts-Denken. Viele Menschen mit ADHS empfinden, dass Putzen nur zählt, wenn sie das ganze Haus perfekt machen, sodass die Aufgabe zu etwas so Riesigem anschwillt, dass das Gehirn sich weigert, überhaupt zu beginnen. Das Chaos wächst dann, bis es zur echten Krise wird, die endlich genug Dringlichkeit und Adrenalin erzeugt, um zu handeln – in einem erschöpfenden und nicht haltbaren Kreislauf.`,
      `Der Ausweg ist, den ersten Schritt fast lächerlich klein zu machen. Statt „die Küche putzen" wird die Aufgabe „einen Abschnitt der Arbeitsfläche frei räumen". Einen Timer auf nur fünf oder zehn Minuten zu stellen, wirkt Wunder, weil es deinem Gehirn einen klaren, begrenzten Endpunkt und die volle Erlaubnis gibt, aufzuhören, wenn er klingelt. Meistens ist das Anfangen der schwerste Teil, und ein wenig Schwung trägt dich weiter, als du erwartet hast.`,
      `Sich etwas Dopamin zu leihen, macht das Ganze leichter. Eine Lieblings-Playlist, ein fesselnder Podcast oder ein Hörbuch verwandeln eine langweilige Aufgabe in etwas Erträgliches oder sogar Angenehmes. Body Doubling hilft auch, denn neben einer Freundin, einem Partner oder sogar bei einem Videoanruf zu putzen, hält dich verankert, und dir selbst eine kleine, konkrete Belohnung am Ende zu versprechen, gibt deinem Gehirn etwas Greifbares, worauf es zugehen kann.`,
      `Es hilft auch, einen Reset statt einen Grundputz anzustreben. Dein Ziel ist an den meisten Tagen einfach, den Raum wieder funktional zu machen, nicht magazin-perfekt, und „gut genug" ist eine völlig legitime Ziellinie. Putzutensilien sichtbar und griffbereit zu halten, deine Ansprüche bewusst zu senken und einen Raum oder sogar eine Fläche nach der anderen anzugehen, verringern alle die Reibung, die dich vom Anfangen abhält.`,
      `Am wichtigsten: lass das moralische Gewicht los, das du an ein aufgeräumtes Zuhause geknüpft hast. Ein unordentlicher Raum ist kein Beweis für einen unordentlichen Charakter; er ist schlicht ein Zeichen, dass Standard-Putztipps nie für die Art gemacht waren, wie dein Gehirn funktioniert. Mit winzigen Schritten, einem Timer, etwas Dopamin und sehr viel weniger Scham wird ein ruhigeres Zuhause weit erreichbarer – und ein sanfter Planer, der die Arbeit in kleine Stücke zerlegt, kann überraschend viel dieser Last für dich tragen.`,
    ],
  },
  'why-adhd-brains-struggle-with-planning': {
    de: [
      `Wenn du ADHS hast, fühlt sich Planung wahrscheinlich an, als würdest du Wasser in den Händen halten wollen. Du startest mit guten Vorsätzen – ein frischer Planer, ein neues System, ein optimistischer Montagmorgen – und irgendwie ist bis Dienstag schon alles wieder zerfallen. Das ist kein Charakterfehler. Das ist Neurowissenschaft.`,
      `ADHS betrifft den präfrontalen Kortex, den Teil des Gehirns, der für die exekutiven Funktionen zuständig ist – Planen, Priorisieren, Zeitmanagement und das Beginnen von Aufgaben. Wenn dieses System nicht so funktioniert wie bei neurotypischen Menschen, helfen herkömmliche Planungsmethoden nicht nur nicht. Sie machen es sogar schlimmer.`,
      `Herkömmliche Planer setzen voraus, dass du auf eine Liste schaust und dich motiviert fühlst, anzufangen. Für ADHS-Gehirne funktioniert Motivation nicht so. ADHS-Gehirne werden von Interesse, Dringlichkeit, Neuheit und Herausforderung angetrieben – nicht von Wichtigkeit oder Priorität. Eine Aufgabe kann entscheidend wichtig sein und sich trotzdem unmöglich anfühlen, während eine völlig belanglose, aber interessante Aufgabe sofort erledigt wird.`,
      `Zeitblindheit ist ein weiterer wichtiger Faktor. Die meisten Menschen haben eine innere Uhr, die ihnen hilft, das Vergehen der Zeit zu spüren. ADHS-Gehirnen fehlt das oft – was dazu führt, dass man plötzlich merkt, dass Stunden vergangen sind, oder dass eine Deadline morgen ist, obwohl sie sich wie Wochen entfernt anfühlte.`,
      `Was hilft wirklich? Systeme, die mit diesen Mustern arbeiten statt gegen sie. Energiebasierte Planung (Aufgaben nach deinem natürlichen Energielevel planen). Time-Timer (visuelle Darstellungen des Vergehens der Zeit). Body Doubling (an der Seite einer anderen Person arbeiten). Und die Schamspirale auflösen, die aus dem Scheitern eines Systems entsteht – denn genau diese Scham macht das Anfangen oft noch schwerer.`,
      `Das Ziel ist nicht, dein ADHS-Gehirn zu reparieren. Das Ziel ist, ein Leben zu bauen, das zu dem Gehirn passt, das du hast.`,
    ],
  },
  'dopamine-menu-guide': {
    de: [
      `Ein Dopamin-Menü ist genau das, wonach es klingt: eine kuratierte Liste von Aktivitäten, die deinem Gehirn einen Dopamin-Schub geben, aufgebaut wie eine Speisekarte. Schnelle Kicks. Mittlere Pausen. Optionen zum vollständigen Aufladen. Die Idee ist einfach, aber für ADHS-Gehirne kann sie wirklich lebensverändernd sein.`,
      `ADHS ist in vielerlei Hinsicht eine Störung der Dopaminregulation. Das Gehirn produziert oder verarbeitet Dopamin nicht auf die typische Weise – deshalb suchen ADHS-Gehirne ständig nach Stimulation, Neuheit und Belohnung. Ohne genug Dopamin fühlt sich das Beginnen von Aufgaben unmöglich an. Die Konzentration verflüchtigt sich. Die Motivation verschwindet völlig.`,
      `Ein Dopamin-Menü gibt dir eine vorgeplante, schuldfreie Möglichkeit, deinen Dopaminspiegel zu regulieren. Statt Doomscrolling oder impulsiv eine ganze Tüte Chips zu essen (beides völlig nachvollziehbares dopaminsuchendes Verhalten), hast du Optionen bereit. Optionen, die du gewählt hast, als dein Gehirn in einem guten Zustand war – nicht, als es verzweifelt war.`,
      `So baust du deins: Beginne damit, Aktivitäten aufzulisten, die dich wirklich aufleuchten lassen. Nicht Dinge, die du genießen solltest – Dinge, die tatsächlich wirken. In der Küche tanzen. Ein bestimmter YouTube-Kanal. Ein Fünf-Minuten-Spaziergang. Einer Freundin etwas Nettes schreiben. Ordne sie dann nach Zeit- und Energieaufwand.`,
      `Schnelle Kicks (1–5 Minuten): Dinge, die du zwischen Aufgaben tun kannst, ohne den Schwung zu verlieren. Mittlere Pausen (10–20 Minuten): echte Erholungszeit. Tiefes Aufladen (30+ Minuten): für die Momente, in denen du wirklich erschöpft bist. Der Schlüssel ist, die Liste bereit zu haben, bevor du sie brauchst – denn wenn das Dopamin niedrig ist, fällt das Entscheiden noch schwerer.`,
      `Druck sie aus. Häng sie irgendwo gut sichtbar auf. Und denk daran: dein Dopamin-Menü zu nutzen, ist kein Aufschieben. Es ist Pflege.`,
    ],
  },
  'time-blindness-adhd': {
    de: [
      `Zeitblindheit gehört zu den am meisten missverstandenen Aspekten von ADHS. Es ist nicht so, dass Menschen mit ADHS sich nicht um Zeit kümmern, dass sie verantwortungslos wären oder sich einfach „mehr anstrengen" müssten. Zeitblindheit ist neurologisch – das ADHS-Gehirn erlebt Zeit wirklich anders.`,
      `Dr. Russell Barkley, einer der führenden ADHS-Forscher, beschreibt es so: Die meisten Menschen erleben Zeit als einen kontinuierlichen Fluss, den sie spüren können. ADHS-Gehirne neigen dazu, nur zwei Zeiten zu erleben: jetzt und nicht jetzt. Der Abstand zwischen „in einer Stunde" und „in drei Wochen" ist im Grunde derselbe – beides ist „nicht jetzt".`,
      `Das erklärt so vieles. Warum Deadlines weit weg wirken und dann plötzlich zu nah sind. Warum sich 20 Minuten unter der Dusche wie 5 anfühlen. Warum du nicht spürst, dass du zu spät dran bist, bis du schon sehr spät dran bist. Warum Hyperfokus Stunden verschlingen kann, ohne dass du es merkst.`,
      `Was hilft? Zeit sichtbar machen. Eine große analoge Uhr an deinem Arbeitsplatz. Ein Time-Timer (ein visueller Timer, der das Vergehen der Zeit als schrumpfenden roten Bogen zeigt). Wecker stellen – nicht nur für den Moment, in dem du los musst, sondern auch für 30 Minuten vorher, 15 Minuten vorher. In zeitlich begrenzten Blöcken arbeiten statt in offenen Sitzungen.`,
      `Übergangswarnungen helfen ebenfalls enorm – gib dir selbst eine Vorwarnung von 5 Minuten, bevor du die Aufgabe wechselst, statt zu erwarten, dass dein Gehirn sofort umschaltet. Viele ADHS-Gehirne empfinden Übergänge als wirklich schmerzhaft, und ein Teil davon ist der abrupte Sprung vom „jetzt" hin zu der plötzlichen Notwendigkeit, „nicht jetzt"-Aufgaben anzuerkennen.`,
      `Zeitblindheit ist real. Sie ist keine Ausrede – sie ist ein Symptom. Und wie alle ADHS-Symptome reagiert sie am besten auf Anpassung statt auf Bestrafung.`,
    ],
  },
  'habit-stacking-adhd': {
    de: [
      `Die meisten Ratschläge zu Gewohnheiten sind für neurotypische Gehirne gemacht. Mach es 21 Tage lang jeden Tag, und es wird automatisch. Wähle einen Auslöser, eine Routine und eine Belohnung. Bau deine Willenskraft auf. Für ADHS-Gehirne scheitern diese Ratschläge oft völlig – nicht weil der Rat falsch wäre, sondern weil er einen konstanten, vorhersehbaren inneren Zustand voraussetzt, den ADHS schlicht nicht liefert.`,
      `Habit Stacking ist anders. Statt zu versuchen, isolierte Gewohnheiten durch Wiederholung aufzubauen, knüpfst du neue Verhaltensweisen an bestehende. Die bestehende Gewohnheit wird zum Auslöser. Das funktioniert für ADHS-Gehirne viel besser, weil es eine der größten Hürden beseitigt: sich daran zu erinnern, das Ding überhaupt zu tun.`,
      `Die wichtigste Anpassung für ADHS ist, kleiner anzufangen, als du denkst. Peinlich klein. Das Ziel einer neuen Gewohnheit ist nicht, jeden Tag die ganze Sache zu tun – sondern das Verhalten automatisch zu machen. Eine Ein-Minuten-Gewohnheit, die du jeden Tag tust, ist unendlich wertvoller als eine 20-Minuten-Gewohnheit, die du dreimal tust und dann aufgibst.`,
      `Knüpf deine neue Gewohnheit an etwas, das ohnehin zuverlässig passiert. Nachdem ich meinen Morgenkaffee gemacht habe → schreibe ich drei Vorsätze für den Tag. Nachdem ich mich an meinen Schreibtisch gesetzt habe → mache ich einen 2-minütigen Brain Dump. Nachdem ich mir abends die Zähne geputzt habe → schreibe ich die erste Aufgabe von morgen auf einen Zettel.`,
      `Rechne mit Unbeständigkeit. ADHS bedeutet, dass deine Kapazität von Tag zu Tag enorm schwankt. An schlechten Tagen sieht deine Gewohnheit vielleicht wie eine 10-Sekunden-Version aus. Das zählt trotzdem. Die Serie ist nicht der Punkt – die Richtung ist es.`,
      `Und wenn du Tage auslässt? Das ist kein Scheitern. Das ist ADHS. Die Gewohnheit zerbricht nicht durch ausgelassene Tage. Sie stirbt nur, wenn du entscheidest, dass sie tot ist. Fang einfach wieder an. Jeder Tag ist eine neue Chance, das Leben aufzubauen, zu dem dein Gehirn fähig ist.`,
    ],
  },
  'do-i-have-adhd-test': {
    de: [
      `Wenn du dich um 1 Uhr nachts dabei ertappt hast, „habe ich ADHS" zu googeln, bist du in guter Gesellschaft. Für sehr viele Erwachsene – besonders Frauen und Menschen, die in der Schule gut waren – kommt die Frage erst auf, wenn das Leben kompliziert genug wird, dass die Bewältigungsstrategien nicht mehr greifen. Ein fordernder Job, Elternschaft oder einfach das eigene Leben zu führen kann lebenslange Muster plötzlich unübersehbar machen.`,
      `ADHS bei Erwachsenen sieht selten aus wie das Klischee eines hyperaktiven Kindes, das von den Wänden abprallt. Es sieht aus wie ein brillanter Mensch, der den Bericht nicht anfangen kann, der morgen fällig ist. Es sieht aus wie das Vergessen von Terminen trotz drei Erinnerungen, vierzig offene Browser-Tabs und hundert weitere im Kopf, und die Erschöpfung durch Aufgaben, die für alle anderen mühelos scheinen. Der Kampf ist real, und er ist keine Frage der Willenskraft.`,
      `Es gibt drei Erscheinungsformen. Der vorwiegend unaufmerksame Typ dreht sich um Konzentration, Gedächtnis und Organisation – das „in Gedanken verloren"-Muster, das oft völlig übersehen wird. Der vorwiegend hyperaktiv-impulsive Typ dreht sich um Unruhe, Impulsivität und emotionale Intensität – das „immer an"-Muster. Der kombinierte Typ, der am häufigsten ist, bedeutet, dass du deutliche Merkmale aus beiden erlebst, und das Gleichgewicht kann sich je nach Stress, Umgebung und der Aufgabe vor dir verschieben.`,
      `Ein paar Anzeichen tauchen immer wieder auf: Schwierigkeiten, Aufgaben zu beginnen, selbst wenn du sie wirklich tun willst, Zeitblindheit (Deadlines wirken weit weg und sind dann plötzlich da), ständig Dinge verlieren, Hyperfokus auf das, was dich interessiert, während alles andere liegen bleibt, und ein Nervensystem, das intensiver reagiert, als die Situation zu verlangen scheint. Keines davon allein bedeutet ADHS – aber ein beständiges Bündel über Jahre hinweg ist es wert, dass man hinschaut.`,
      `Eine Selbsteinschätzung kann dich nicht diagnostizieren, und das sollte sie auch nicht versuchen. Was eine gute Einschätzung tun kann: dir helfen, Muster in Worte zu fassen, die du seit Jahren spürst, aber nie benannt hast, und dir etwas Konkretes geben, das du zu einer Fachperson mitnehmen kannst. Unser kostenloser ADHS-Test führt dich durch 40 Fragen auf Basis der DSM-5-Kriterien und zeigt dir, zu welchem Typ deine Antworten tendieren – in etwa fünf Minuten, ohne Scham und ohne Fachjargon.`,
      `Wenn dich deine Ergebnisse ansprechen, ist der nächste Schritt ein Gespräch mit einer approbierten Psychiaterin oder einem Psychologen, die eine echte Abklärung vornehmen und Optionen besprechen können. Sei in der Zwischenzeit sanft mit dir. Zu verstehen, wie dein Gehirn funktioniert, heißt nicht, etwas Falsches an dir zu finden – es heißt, endlich ein Leben bauen zu dürfen, das zu dem Gehirn passt, das du tatsächlich hast.`,
    ],
  },
  'adhd-paralysis': {
    de: [
      `ADHS-Paralyse gehört zu den frustrierendsten und am wenigsten verstandenen Seiten von ADHS. Es ist die Erfahrung, genau zu wissen, was du tun musst, es wirklich tun zu wollen, die Folgen des Nichtstuns zu verstehen – und trotzdem völlig unfähig zu sein, anzufangen. Du bist nicht faul. Du vermeidest es nicht absichtlich. Du bist erstarrt.`,
      `Es gibt ein paar Spielarten davon. Aufgaben-Paralyse ist die Unfähigkeit, eine einzelne Aufgabe zu beginnen. Entscheidungs-Paralyse trifft, wenn es zu viele Optionen gibt und dein Gehirn sich schlicht weigert, eine zu wählen. Und Überforderungs-Paralyse stellt sich ein, wenn alles gleich dringend wirkt, sodass du am Ende gar nichts tust – oft begleitet von starker Schuld. Alle drei kommen vom selben Ort: einem exekutiven System, das vorübergehend überlastet ist.`,
      `Die Neurowissenschaft erklärt, warum „mach es einfach" nie funktioniert. Eine Aufgabe zu beginnen verlangt vom Gehirn, den Aufwand abzuschätzen, Schritte zu ordnen und genug Dopamin zu erzeugen, um die Bewegung anzustoßen. In ADHS-Gehirnen ist dieses Anstoß-System unzuverlässig. Wenn eine Aufgabe groß, langweilig oder unklar wirkt, kann das Gehirn die Aktivierungsenergie nicht aufbringen – und je mehr du drückst, desto stärker blockiert es.`,
      `Der Ausweg ist fast nie, härter zu drücken. Es ist, den ersten Schritt absurd klein zu machen. Nicht „die Küche putzen", sondern „eine Tasse in die Spüle stellen". Nicht „den Bericht schreiben", sondern „das Dokument öffnen und den Titel tippen". Das Ziel ist nicht, fertig zu werden – es ist, die Starre zu durchbrechen. Bewegung erzeugt Dopamin, und Dopamin macht den nächsten Schritt möglich. Deshalb fühlt sich Schwung so gut an, sobald er einmal beginnt.`,
      `Was sonst noch wirklich hilft: Body Doubling, bei dem du neben einer anderen Person arbeitest (auch per Videoanruf), damit dein Gehirn sich deren Fokus ausleiht. Die Schritte externalisieren, damit sie auf Papier leben statt im Kopf zu kreisen. Einen Timer auf nur fünf Minuten stellen, mit der ausdrücklichen Erlaubnis, danach aufzuhören. Und ein Brain Dump, um das mentale Durcheinander zu klären, bevor du wählst, was zählt. Jedes davon senkt die Aktivierungsenergie, die die Aufgabe verlangt.`,
      `Vor allem: lass die Scham los. Paralyse ist ein Symptom, kein Charakterfehler, und Scham ist Brennstoff für die Starre – sie lässt die Aufgabe noch bedrohlicher wirken, was dein Gehirn noch fester blockiert. Das Freundlichste und Wirksamste, was du tun kannst, ist, einen festgefahrenen Moment als Information zu behandeln, den Schritt zu verkleinern und dir zu erlauben, schlecht anzufangen. Schlecht anzufangen zählt trotzdem als Anfangen.`,
    ],
  },
  'best-planner-for-adhd': {
    de: [
      `Wenn du einen schönen Planer gekauft, ihn neun Tage lang gewissenhaft genutzt und dann zugesehen hast, wie er zum teuren Briefbeschwerer wurde, dann war weder der Planer das Problem noch du. Die meisten Planer sind für neurotypische Gehirne gemacht – sie setzen voraus, dass du daran denkst, sie zu öffnen, dass dich eine ordentliche Liste motiviert und dass du Zeit als steten, vorhersehbaren Fluss erlebst. ADHS-Gehirne funktionieren nicht so, also bringt dich das Werkzeug leise zum Scheitern.`,
      `Ein ADHS-freundlicher Planer muss etwas anderes leisten. Er muss Zeit externalisieren, weil ADHS-Gehirne sie schwer vergehen spüren. Er muss das Anfangen leicht machen, weil der Aufgabenbeginn der schwierigste Teil ist. Und er muss nachsichtig sein, denn ein System, das dich für einen ausgelassenen Tag bestraft, wird in dem Moment aufgegeben, in dem du in Rückstand gerätst – was bei ADHS unvermeidlich und völlig normal ist.`,
      `Das Erste, worauf du achten solltest, ist eingebaute Aufgabenzerlegung. „Event planen" ist lähmend; „dem Veranstaltungsort schreiben, drei Termine auswählen, die Einladung entwerfen" ist machbar. Ein Planer, der dir Raum gibt, Aufgaben in winzige, konkrete Schritte zu zerlegen, beseitigt die größte Hürde, vor der ADHS-Gehirne stehen. Wenn der Planer dir nur eine leere To-do-Zeile gibt, verlangt er von deiner exekutiven Funktion genau die Arbeit, die ihr am schwersten fällt.`,
      `Das Zweite ist eine energiebasierte Struktur statt einer starren Stundenplanung. ADHS-Energie schwankt dramatisch, und ein Planer, der davon ausgeht, dass du jeden Tag pünktlich um 9 Uhr Tiefarbeit leistest, liegt an den meisten Tagen falsch. Rund um deine natürlichen Energiefenster zu planen – fordernde Aufgaben an energiereiche Zeiten, Admin an energiearme – arbeitet mit deinem Gehirn statt gegen es.`,
      `Das Dritte, und am meisten Übersehene, ist eingebaute Freundlichkeit. Die besten ADHS-Planer machen Platz für Brain Dumps, für „gut genug"-Tage, für das Feiern kleiner Erfolge und für das Neuanfangen ohne Schuld. Sie behandeln einen ausgelassenen Tag als frische Seite, nicht als gebrochene Serie. Das ist nicht weich – es ist strategisch, denn Scham ist einer der größten Gründe, warum ADHS-Systeme zusammenbrechen.`,
      `Genau darum ist das bloom focus Toolkit herum gebaut: Planer, die Aufgaben für dich zerlegen, Struktur rund um Energie statt starrer Uhren, und ein Ton, der dir nie das Gefühl gibt, im Rückstand zu sein. Wenn du dir jeden aufgegebenen Planer selbst vorgeworfen hast, war es vielleicht das Design, das versagt hat – nicht deine Disziplin. Das richtige Werkzeug fühlt sich weniger wie ein Test an, den du immer wieder nicht bestehst, und mehr wie eine Hand in deinem Rücken.`,
    ],
  },
  'adhd-in-women': {
    de: [
      `Jahrzehntelang wurde ADHS fast ausschließlich an kleinen Jungen erforscht – den hyperaktiven, die im Unterricht nicht stillsitzen konnten. Das Ergebnis ist ein diagnostisches Bild, das verfehlt, wie ADHS bei Frauen und Mädchen am häufigsten auftritt – weshalb so viele Frauen erst mit dreißig, vierzig oder später diagnostiziert werden, häufig nachdem ein eigenes Kind abgeklärt wird und die Symptome plötzlich vertraut wirken.`,
      `Bei Frauen ist ADHS häufiger unaufmerksam als hyperaktiv – und unaufmerksames ADHS ist leise. Es stört den Unterricht nicht. Es sieht aus wie Tagträumen, wie „zerstreut" oder „schusselig" sein, wie ein kluges Mädchen, das hinter seinem Potenzial zurückbleibt. Weil es niemandem sonst Ärger macht, wird es übersehen, und das Mädchen lernt, es zu maskieren – oft zu enormen inneren Kosten.`,
      `Dieses Maskieren ist ein riesiger Teil der Geschichte. Viele Frauen mit ADHS werden zu intensiven Perfektionistinnen und Über-Vorbereiterinnen und bauen aufwendige Systeme, um ein Gehirn auszugleichen, das sie nicht verstehen. Von außen wirken sie organisiert und leistungsstark. Innen sind sie erschöpft, ängstlich und überzeugt, nur eine verrutschte Maske davon entfernt zu sein, dass alle herausfinden, wie hart sie in Wahrheit arbeiten, um mitzuhalten.`,
      `Deshalb wird ADHS bei Frauen so oft als Angst oder Depression fehldiagnostiziert. Diese Zustände können durchaus gleichzeitig bestehen – aber häufig ist die Angst eine Folge jahrelangen undiagnostizierten ADHS: der chronische Stress verpasster Deadlines, die Scham des Vergessens, der Tribut, doppelt so hart für dasselbe Ergebnis zu arbeiten. Die Angst zu behandeln, ohne das ADHS darunter zu erkennen, erfasst nur die Hälfte des Bildes.`,
      `Hormone fügen eine weitere Ebene hinzu, die die alte Forschung völlig ignoriert hat. Östrogen beeinflusst Dopamin, daher verstärken sich ADHS-Symptome oft prämenstruell, nach der Geburt und in der Perimenopause. Viele Frauen beschreiben, dass ihre Symptome mit vierzig plötzlich unbeherrschbar werden – nicht weil etwas neu falsch ist, sondern weil eine hormonelle Verschiebung den Puffer entfernt hat, auf den sie sich jahrelang unbewusst verlassen haben.`,
      `Wenn sich irgendetwas davon liest wie dein eigenes Tagebuch, dann bist du nicht kaputt, nicht dramatisch und bildest dir nichts ein. Du hast vielleicht einfach ein Gehirn, das nie zu seinen eigenen Bedingungen abgeklärt wurde. Eine Selbsteinschätzung kann dir helfen, das Muster zu benennen, und eine approbierte Fachperson kann dir eine echte Abklärung geben. Es zu verstehen ändert alles – nicht weil du ein anderer Mensch wirst, sondern weil du endlich aufhören darfst, dir selbst Vorwürfe zu machen, einer zu sein.`,
    ],
  },
}

// ---- helpers ----
export function blogTitle(slug: string, lang: Lang, enTitle: string) {
  if (lang === 'en') return enTitle
  return articleMeta[slug]?.[lang]?.title || enTitle
}
export function blogExcerpt(slug: string, lang: Lang, enExcerpt: string) {
  if (lang === 'en') return enExcerpt
  return articleMeta[slug]?.[lang]?.excerpt || enExcerpt
}
export function blogTag(enTag: string, lang: Lang) {
  if (lang === 'en') return enTag
  return blogTagMap[lang][enTag] || enTag
}
export function blogBody(slug: string, lang: Lang): string[] {
  if (lang !== 'en') {
    const t = articleBody[slug]?.[lang]
    if (t && t.length) return t
  }
  return articleContentEN[slug] || []
}
export function readTimeLabel(lang: Lang, raw: string) {
  const n = parseInt(String(raw).replace(/\D+/g, '')) || 0
  if (lang === 'de') return `${n} Min. Lesezeit`
  if (lang === 'fr') return `${n} min de lecture`
  if (lang === 'es') return `${n} min de lectura`
  return raw
}

// ---- French (FR) ----
const FR_META: Record<string, { title: string; excerpt: string }> = {
  'adhd-rejection-sensitive-dysphoria': { title: `TDAH et dysphorie sensible au rejet : pourquoi la critique fait si mal`, excerpt: `Si une petite critique peut gâcher toute ta journée, tu n'es pas trop sensible – tu vis peut-être la RSD, l'une des facettes les plus douloureuses et les moins connues du TDAH.` },
  'adhd-and-sleep': { title: `TDAH et sommeil : pourquoi ton cerveau ne s'éteint pas la nuit`, excerpt: `Pensées qui s'emballent à minuit, un second souffle pile quand tu devrais dormir, des matins impossibles – TDAH et troubles du sommeil vont de pair. Voici pourquoi, et ce qui aide.` },
  'body-doubling-adhd': { title: `Body doubling : l'astuce de concentration TDAH qui marche vraiment`, excerpt: `Pourquoi est-il tellement plus facile de travailler quand quelqu'un d'autre est dans la pièce ? Le body doubling en fait une stratégie – l'un des outils de concentration TDAH les plus fiables qui soient.` },
  'adhd-burnout': { title: `Burnout TDAH : les signes que tu tournes à vide (et comment récupérer)`, excerpt: `Le burnout TDAH n'est pas une fatigue ordinaire – c'est l'effondrement qui survient après des mois de masquage et de surcompensation. Voici comment le repérer et récupérer en douceur.` },
  'how-to-clean-with-adhd': { title: `Comment nettoyer ta maison avec un TDAH sans la surcharge`, excerpt: `Si le ménage semble impossible jusqu'à devenir une crise, tu n'es pas paresseux·se – ton cerveau a juste besoin d'une autre approche. Voici comment nettoyer avec un cerveau TDAH, pas à pas, en douceur.` },
}
for (const [slug, m] of Object.entries(FR_META)) {
  articleMeta[slug] = { ...(articleMeta[slug] || {}), fr: m }
}

const FR_BODY: Record<string, string[]> = {
  'why-adhd-brains-struggle-with-planning': [
    `Si tu as un TDAH, planifier te donne probablement l'impression d'essayer de retenir de l'eau dans tes mains. Tu commences avec de bonnes intentions – un agenda tout neuf, un nouveau système, un lundi matin optimiste – et, on ne sait comment, dès le mardi tout s'est déjà effondré. Ce n'est pas un défaut de caractère. C'est de la neuroscience.`,
    `Le TDAH touche le cortex préfrontal, la partie du cerveau responsable des fonctions exécutives – planifier, prioriser, gérer le temps et démarrer les tâches. Quand ce système ne fonctionne pas comme chez les personnes neurotypiques, les méthodes de planification classiques ne se contentent pas d'être inutiles. Elles aggravent activement les choses.`,
    `Les agendas classiques supposent que tu peux regarder une liste et te sentir motivé·e à commencer. Pour les cerveaux TDAH, la motivation ne fonctionne pas ainsi. Les cerveaux TDAH sont mus par l'intérêt, l'urgence, la nouveauté et le défi – pas par l'importance ou la priorité. Une tâche peut être cruciale et sembler malgré tout impossible à démarrer, tandis qu'une tâche totalement accessoire mais intéressante se fait immédiatement.`,
    `La cécité temporelle est un autre facteur majeur. La plupart des gens ont une horloge interne qui les aide à sentir le temps passer. Les cerveaux TDAH en sont souvent dépourvus – d'où l'expérience de se rendre compte soudain que des heures ont filé, ou qu'une échéance est pour demain alors qu'elle semblait à des semaines.`,
    `Qu'est-ce qui aide vraiment ? Des systèmes qui travaillent avec ces schémas plutôt que contre eux. La planification basée sur l'énergie (organiser les tâches selon tes niveaux d'énergie naturels). Les minuteurs visuels (des représentations du temps qui s'écoule). Le body doubling (travailler aux côtés de quelqu'un d'autre). Et dissoudre la spirale de honte qui naît de l'échec d'un système – parce que c'est souvent cette honte qui rend le démarrage encore plus difficile.`,
    `Le but n'est pas de réparer ton cerveau TDAH. Le but est de construire une vie qui fonctionne pour le cerveau que tu as.`,
  ],
  'dopamine-menu-guide': [
    `Un menu dopamine est exactement ce que son nom indique : une liste soignée d'activités qui donnent à ton cerveau un coup de dopamine, organisée comme une carte de restaurant. Des doses rapides. Des pauses moyennes. Des options de recharge complète. L'idée est simple, mais pour les cerveaux TDAH, elle peut vraiment changer la vie.`,
    `Le TDAH est, à bien des égards, un trouble de la régulation de la dopamine. Le cerveau ne produit ni ne traite la dopamine de la manière habituelle – c'est pourquoi les cerveaux TDAH recherchent en permanence stimulation, nouveauté et récompense. Sans assez de dopamine, démarrer une tâche semble impossible. La concentration s'évapore. La motivation disparaît complètement.`,
    `Un menu dopamine te donne une façon préparée à l'avance, et sans culpabilité, de réguler ton niveau de dopamine. Au lieu de scroller sans fin ou d'engloutir impulsivement un paquet de chips entier (deux comportements de recherche de dopamine tout à fait compréhensibles), tu as des options prêtes. Des options que tu as choisies quand ton cerveau allait bien, pas quand il était à bout.`,
    `Comment créer le tien : commence par lister des activités qui t'illuminent vraiment. Pas des choses que tu penses devoir apprécier – des choses qui fonctionnent réellement. Danser dans ta cuisine. Une chaîne YouTube précise. Une marche de cinq minutes. Envoyer un mot gentil à une amie. Classe-les ensuite selon le temps et l'énergie qu'elles demandent.`,
    `Doses rapides (1 à 5 minutes) : des choses à faire entre deux tâches sans perdre ton élan. Pauses moyennes (10 à 20 minutes) : un vrai temps de recharge. Recharge profonde (30 minutes et plus) : pour les moments où tu es réellement vidé·e. La clé est d'avoir la liste prête avant d'en avoir besoin – car lorsque la dopamine est basse, décider est encore plus dur.`,
    `Imprime-la. Mets-la quelque part bien en vue. Et souviens-toi : utiliser ton menu dopamine, ce n'est pas procrastiner. C'est de l'entretien.`,
  ],
  'time-blindness-adhd': [
    `La cécité temporelle est l'un des aspects les plus mal compris du TDAH. Ce n'est pas que les personnes avec un TDAH se moquent du temps, qu'elles soient irresponsables ou qu'elles aient juste besoin de « faire plus d'efforts ». La cécité temporelle est neurologique – le cerveau TDAH vit vraiment le temps différemment.`,
    `Le Dr Russell Barkley, l'un des grands chercheurs sur le TDAH, le décrit ainsi : la plupart des gens vivent le temps comme un flux continu qu'ils peuvent ressentir. Les cerveaux TDAH ont tendance à ne vivre que deux temps : maintenant, et pas maintenant. La distance entre « dans une heure » et « dans trois semaines » est au fond la même – les deux sont « pas maintenant ».`,
    `Cela explique tant de choses. Pourquoi les échéances semblent lointaines puis soudain trop proches. Pourquoi 20 minutes sous la douche en paraissent 5. Pourquoi tu ne sens pas que tu es en retard avant d'être déjà très en retard. Pourquoi l'hyperfocus peut engloutir des heures sans que tu le remarques.`,
    `Qu'est-ce qui aide ? Rendre le temps visible. Une grande horloge analogique sur ton espace de travail. Un minuteur visuel (qui montre le temps qui passe sous forme d'arc rouge qui rétrécit). Régler des alarmes non seulement pour le moment du départ, mais aussi pour 30 minutes avant, 15 minutes avant. Travailler en blocs minutés plutôt qu'en sessions ouvertes.`,
    `Les avertissements de transition aident aussi énormément – accorde-toi un préavis de 5 minutes avant de changer de tâche, au lieu d'attendre de ton cerveau qu'il bascule instantanément. Beaucoup de cerveaux TDAH trouvent les transitions vraiment douloureuses, en partie à cause du passage brutal du « maintenant » à la nécessité soudaine de reconnaître les tâches « pas maintenant ».`,
    `La cécité temporelle est réelle. Ce n'est pas une excuse – c'est un symptôme. Et comme tous les symptômes du TDAH, elle répond mieux à l'aménagement qu'à la punition.`,
  ],
  'habit-stacking-adhd': [
    `La plupart des conseils sur les habitudes sont conçus pour les cerveaux neurotypiques. Fais-le chaque jour pendant 21 jours et cela devient automatique. Choisis un déclencheur, une routine et une récompense. Renforce ta volonté. Pour les cerveaux TDAH, ces conseils échouent souvent complètement – non parce qu'ils sont faux, mais parce qu'ils supposent un état intérieur constant et prévisible que le TDAH ne fournit tout simplement pas.`,
    `L'empilement d'habitudes est différent. Au lieu d'essayer de bâtir des habitudes isolées par la répétition, tu rattaches de nouveaux comportements à des comportements existants. L'habitude déjà en place devient le déclencheur. Cela fonctionne bien mieux pour les cerveaux TDAH, car cela supprime l'un des plus grands obstacles : se souvenir de faire la chose.`,
    `L'adaptation essentielle pour le TDAH est de commencer plus petit que tu ne le penses. Petit au point d'en être gênant. Le but d'une nouvelle habitude n'est pas de faire la chose entière chaque jour – c'est de rendre le comportement automatique. Une habitude d'une minute que tu fais chaque jour vaut infiniment plus qu'une habitude de 20 minutes que tu fais trois fois avant d'abandonner.`,
    `Rattache ta nouvelle habitude à quelque chose qui se produit déjà de façon fiable. Après avoir préparé mon café du matin → j'écris trois intentions pour la journée. Après m'être assis·e à mon bureau → je fais un brain dump de 2 minutes. Après m'être brossé les dents le soir → je note la première tâche de demain sur un post-it.`,
    `Attends-toi à l'irrégularité. Le TDAH signifie que ta capacité varie énormément d'un jour à l'autre. Les mauvais jours, ton habitude ressemblera peut-être à une version de 10 secondes. Cela compte quand même. La série n'est pas l'essentiel – la direction l'est.`,
    `Et si tu sautes des jours ? Ce n'est pas un échec. C'est le TDAH. L'habitude ne se brise pas parce que tu as sauté des jours. Elle ne meurt que si tu décides qu'elle est morte. Recommence, tout simplement. Chaque jour est une nouvelle chance de bâtir la vie dont ton cerveau est capable.`,
  ],
  'do-i-have-adhd-test': [
    `Si tu t'es déjà surpris·e à taper « est-ce que j'ai un TDAH » à 1 h du matin, tu es en bonne compagnie. Pour énormément d'adultes – surtout les femmes et les personnes qui réussissaient à l'école – la question ne surgit que lorsque la vie devient assez compliquée pour que les stratégies d'adaptation cessent de fonctionner. Un travail exigeant, la parentalité ou simplement gérer sa propre vie peuvent soudain rendre des schémas de toujours impossibles à ignorer.`,
    `Chez l'adulte, le TDAH ressemble rarement au cliché de l'enfant hyperactif qui rebondit sur les murs. Il ressemble à une personne brillante incapable de commencer le rapport à rendre demain. Il ressemble à oublier des rendez-vous malgré trois rappels, à avoir quarante onglets ouverts et cent autres dans la tête, et à être épuisé·e par des tâches qui semblent sans effort pour tout le monde. La lutte est réelle, et ce n'est pas une question de volonté.`,
    `Il existe trois présentations. Le type à prédominance inattentive tourne autour de l'attention, de la mémoire et de l'organisation – le schéma « perdu dans ses pensées » qui passe souvent complètement inaperçu. Le type à prédominance hyperactive-impulsive tourne autour de l'agitation, de l'impulsivité et de l'intensité émotionnelle – le schéma « toujours en marche ». Le type combiné, le plus fréquent, signifie que tu vis des traits importants des deux, et l'équilibre peut se déplacer selon le stress, l'environnement et la tâche devant toi.`,
    `Quelques signes reviennent encore et encore : la difficulté à démarrer des tâches même quand tu veux vraiment les faire, la cécité temporelle (les échéances semblent lointaines puis arrivent d'un coup), perdre des objets sans arrêt, hyperfocaliser sur ce qui t'intéresse pendant que tout le reste glisse, et un système nerveux qui réagit plus intensément que la situation ne semble l'exiger. Aucun de ces signes seul ne signifie TDAH – mais un ensemble constant sur des années mérite qu'on y prête attention.`,
    `Une auto-évaluation ne peut pas te diagnostiquer, et elle ne devrait pas essayer. Ce qu'une bonne évaluation peut faire : t'aider à mettre des mots sur des schémas que tu ressens depuis des années sans jamais les nommer, et te donner quelque chose de concret à apporter à un·e professionnel·le. Notre test TDAH gratuit te guide à travers 40 questions fondées sur les critères du DSM-5 et te montre vers quel type tes réponses penchent – en environ cinq minutes, sans honte et sans jargon.`,
    `Si tes résultats résonnent, l'étape suivante est un échange avec un·e psychiatre ou psychologue agréé·e, qui pourra réaliser une véritable évaluation et discuter des options. En attendant, sois doux·ce avec toi-même. Comprendre comment ton cerveau fonctionne, ce n'est pas trouver quelque chose qui cloche chez toi – c'est enfin pouvoir construire une vie qui convient au cerveau que tu as vraiment.`,
  ],
  'adhd-paralysis': [
    `La paralysie TDAH est l'une des facettes les plus frustrantes et les moins comprises du TDAH. C'est l'expérience de savoir exactement ce que tu dois faire, de vouloir vraiment le faire, de comprendre les conséquences de ne pas le faire – et d'être malgré tout totalement incapable de commencer. Tu n'es pas paresseux·se. Tu ne l'évites pas exprès. Tu es figé·e.`,
    `Il en existe plusieurs variantes. La paralysie de la tâche, c'est l'incapacité de démarrer une seule tâche. La paralysie du choix frappe quand il y a trop d'options et que ton cerveau refuse simplement d'en choisir une. Et la paralysie de la surcharge survient quand tout semble également urgent, si bien que tu finis par ne rien faire du tout, souvent en ressentant une culpabilité intense. Les trois viennent du même endroit : un système exécutif momentanément surchargé.`,
    `La neuroscience aide à comprendre pourquoi « fais-le, c'est tout » ne marche jamais. Démarrer une tâche demande à ton cerveau d'estimer l'effort, d'ordonner les étapes et de générer assez de dopamine pour amorcer le mouvement. Dans les cerveaux TDAH, ce système d'amorçage est peu fiable. Quand une tâche paraît grande, ennuyeuse ou floue, le cerveau ne parvient pas à mobiliser l'énergie d'activation – et plus tu forces, plus il se bloque.`,
    `La sortie n'est presque jamais de forcer davantage. C'est de rendre le premier pas absurdement petit. Pas « nettoyer la cuisine » mais « mettre une tasse dans l'évier ». Pas « écrire le rapport » mais « ouvrir le document et taper le titre ». Le but n'est pas de finir – c'est de briser le gel. Le mouvement crée de la dopamine, et la dopamine rend le pas suivant possible. C'est pour ça que l'élan fait tellement de bien une fois lancé.`,
    `Ce qui aide vraiment aussi : le body doubling, où tu travailles aux côtés d'une autre personne (même en visio) pour que ton cerveau emprunte sa concentration. Externaliser les étapes, pour qu'elles vivent sur le papier au lieu de tourner dans ta tête. Régler un minuteur sur seulement cinq minutes, avec la pleine permission de t'arrêter ensuite. Et un brain dump pour dégager le fouillis mental avant de choisir ce qui compte. Chacun de ces gestes abaisse l'énergie d'activation que la tâche réclame.`,
    `Surtout, lâche la honte. La paralysie est un symptôme, pas un défaut de caractère, et la honte est du carburant pour le gel – elle rend la tâche encore plus menaçante, ce qui bloque ton cerveau plus fort. La chose la plus douce et la plus efficace que tu puisses faire, c'est de traiter un moment de blocage comme une information, de réduire le pas et de t'autoriser à commencer mal. Commencer mal compte quand même comme commencer.`,
  ],
  'best-planner-for-adhd': [
    `Si tu as acheté un bel agenda, l'as utilisé religieusement pendant neuf jours, puis l'as regardé devenir un presse-papier hors de prix, le problème n'était ni l'agenda ni toi. La plupart des agendas sont conçus pour les cerveaux neurotypiques – ils supposent que tu penseras à les ouvrir, qu'une liste bien rangée te motivera et que tu vis le temps comme un flux régulier et prévisible. Les cerveaux TDAH ne fonctionnent pas ainsi, alors l'outil te prépare discrètement à l'échec.`,
    `Un agenda adapté au TDAH doit faire quelque chose de différent. Il doit externaliser le temps, parce que les cerveaux TDAH le sentent mal passer. Il doit rendre le démarrage facile, parce que l'initiation des tâches est la partie la plus difficile. Et il doit être indulgent, car un système qui te punit pour un jour manqué sera abandonné dès que tu prendras du retard – ce qui, avec un TDAH, est inévitable et tout à fait normal.`,
    `La première chose à rechercher, c'est une décomposition des tâches intégrée. « Organiser un événement » est paralysant ; « écrire au lieu, choisir trois dates, rédiger l'invitation » est faisable. Un agenda qui te laisse de la place pour découper les tâches en petites étapes concrètes supprime le plus grand obstacle des cerveaux TDAH. Si l'agenda ne te donne qu'une ligne de to-do vide, il demande à ta fonction exécutive le travail qu'elle est le moins capable de faire.`,
    `La deuxième, c'est une structure basée sur l'énergie plutôt qu'un emploi du temps rigide à l'heure. L'énergie TDAH fluctue énormément, et un agenda qui suppose que tu feras un travail profond à 9 h pile chaque jour aura tort la plupart du temps. Planifier autour de tes fenêtres d'énergie naturelles – les tâches exigeantes aux moments d'énergie haute, l'administratif aux moments d'énergie basse – travaille avec ton cerveau plutôt que contre lui.`,
    `La troisième, et la plus négligée, c'est une bienveillance intégrée. Les meilleurs agendas TDAH font de la place pour les brain dumps, pour les journées « assez bien », pour célébrer les petites victoires et pour recommencer sans culpabilité. Ils traitent un jour manqué comme une page neuve, pas comme une série brisée. Ce n'est pas mièvre – c'est stratégique, car la honte est l'une des plus grandes raisons pour lesquelles les systèmes TDAH s'effondrent.`,
    `C'est exactement autour de ça qu'est construite la boîte à outils bloom focus : des agendas qui décomposent les tâches pour toi, une structure organisée autour de l'énergie plutôt que d'horloges rigides, et un ton qui ne te donne jamais l'impression d'être en retard. Si tu t'es reproché chaque agenda abandonné, c'est peut-être le design qui t'a fait défaut – pas ta discipline. Le bon outil ressemble moins à un test que tu rates sans cesse qu'à une main posée dans ton dos.`,
  ],
  'adhd-in-women': [
    `Pendant des décennies, le TDAH a été étudié presque exclusivement chez les jeunes garçons – les hyperactifs qui ne tenaient pas en place en classe. Le résultat est un tableau diagnostique qui passe à côté de la façon dont le TDAH se manifeste le plus souvent chez les femmes et les filles – c'est pourquoi tant de femmes ne sont diagnostiquées qu'à trente, quarante ans ou plus, souvent après l'évaluation de leur propre enfant, quand les symptômes deviennent soudain familiers.`,
    `Chez les femmes, le TDAH est plus souvent inattentif qu'hyperactif – et le TDAH inattentif est silencieux. Il ne perturbe pas la classe. Il ressemble à de la rêverie, à être « tête en l'air » ou « éparpillée », à une fille intelligente qui n'exploite pas son potentiel. Parce qu'il ne dérange personne d'autre, on le néglige, et la fille apprend à le masquer – souvent à un coût intérieur énorme.`,
    `Ce masquage est une part immense de l'histoire. Beaucoup de femmes avec un TDAH deviennent d'intenses perfectionnistes et sur-préparatrices, bâtissant des systèmes élaborés pour compenser un cerveau qu'elles ne comprennent pas. De l'extérieur, elles paraissent organisées et performantes. À l'intérieur, elles sont épuisées, anxieuses, et convaincues qu'un masque qui glisse suffirait pour que tout le monde découvre à quel point elles travaillent dur pour suivre.`,
    `C'est pourquoi le TDAH chez les femmes est si souvent diagnostiqué à tort comme de l'anxiété ou de la dépression. Ces troubles peuvent tout à fait coexister – mais l'anxiété est fréquemment la conséquence d'années de TDAH non diagnostiqué : le stress chronique des échéances manquées, la honte des oublis, le prix de travailler deux fois plus dur pour le même résultat. Traiter l'anxiété sans reconnaître le TDAH en dessous ne s'occupe que de la moitié du tableau.`,
    `Les hormones ajoutent une couche que l'ancienne recherche ignorait totalement. L'œstrogène influence la dopamine, donc les symptômes du TDAH s'intensifient souvent avant les règles, après l'accouchement et pendant la périménopause. Beaucoup de femmes décrivent des symptômes qui deviennent soudain ingérables vers la quarantaine – non parce que quelque chose ne va plus, mais parce qu'un changement hormonal a retiré le tampon sur lequel elles s'appuyaient inconsciemment depuis des années.`,
    `Si quoi que ce soit de tout cela se lit comme ton propre journal intime, tu n'es ni cassée, ni dramatique, ni en train d'inventer. Tu as peut-être simplement un cerveau qui n'a jamais été évalué selon ses propres termes. Une auto-évaluation peut t'aider à nommer le schéma, et un·e professionnel·le agréé·e peut te donner une véritable évaluation. Le comprendre change tout – non parce que tu deviens une autre personne, mais parce que tu peux enfin arrêter de te reprocher d'en être une.`,
  ],
  'adhd-rejection-sensitive-dysphoria': [
    `La dysphorie sensible au rejet, ou RSD, est la douleur émotionnelle intense qui suit un rejet, une critique ou un échec, réels ou perçus. Pour beaucoup de personnes avec un TDAH, c'est le symptôme le plus perturbant de tous, et pourtant presque personne n'est prévenu au moment du diagnostic. Une remarque en passant d'un collègue, un message resté sans réponse, ou une minuscule erreur au travail peuvent chacun déclencher une vague de douleur si forte qu'elle en devient physique, et totalement disproportionnée par rapport à ce qui s'est réellement passé.`,
    `La raison est neurologique, et non une question de susceptibilité. Les cerveaux TDAH régulent les émotions différemment, et les sentiments arrivent plus vite, plus fort, et sont plus difficiles à éteindre. Les mêmes systèmes de dopamine et de noradrénaline qui rendent la concentration difficile rendent aussi l'intensité émotionnelle plus dure à atténuer ; là où une personne neurotypique ressentirait une petite piqûre, un cerveau TDAH peut vivre, en quelques secondes, quelque chose de plus proche d'une véritable dévastation.`,
    `La RSD revêt de nombreux déguisements. Parfois elle ressemble à du people-pleasing, où tu dis oui à tout pour que personne ne soit jamais déçu de toi. Parfois elle ressemble à du perfectionnisme, ou au refus discret d'essayer des choses où tu pourrais échouer. Parfois elle bascule vers l'extérieur en colère ou en défense soudaines. Et très souvent elle ressemble à du retrait : annuler des projets, éviter les retours, ou t'éloigner des gens dès que tu sens que tu pourrais être jugé·e.`,
    `Parce que la douleur est invisible, on dit souvent aux personnes vivant la RSD qu'elles exagèrent ou qu'elles sont dramatiques. Cette réaction aggrave tout, car elle empile de la honte sur un sentiment déjà accablant. Comprendre que la RSD est un schéma reconnu au sein du TDAH, et non un défaut de caractère, est souvent la chose la plus soulageante qu'une personne puisse apprendre, parce qu'elle explique enfin toute une vie de réactions qui n'avaient jamais semblé avoir de sens.`,
    `Ce qui aide, c'est un mélange de nommer et de prendre du recul. Apprendre à reconnaître le moment comme « c'est la RSD, pas la vérité » crée un petit espace entre le sentiment et ta réaction. Attendre avant de répondre à un message déclencheur, confronter ton interprétation aux faits réels et préparer de douces formulations pour recevoir un retour réduisent tous l'intensité. Parler ouvertement avec des personnes de confiance aide aussi : elles peuvent te rappeler qu'un commentaire n'est pas un verdict sur ta valeur.`,
    `Surtout, la RSD répond à l'auto-compassion plutôt qu'à l'autocritique. Le sentiment est réel et il est douloureux, mais il est aussi temporaire, et il passe plus vite quand tu l'accueilles avec douceur au lieu de le combattre. Tu n'es pas « trop », et tu n'es pas cassé·e. Tu as simplement un cerveau qui ressent les choses à plein volume – et cette même intensité, orientée ailleurs, est souvent là d'où viennent aussi ta chaleur et ta créativité.`,
  ],
  'adhd-and-sleep': [
    `Si ton cerveau s'anime à l'instant où ta tête touche l'oreiller, tu es loin d'être seul·e. Les troubles du sommeil sont l'une des facettes les plus fréquentes et les moins évoquées du TDAH, touchant une large majorité des adultes concernés. Le schéma est douloureusement familier : épuisé·e toute la journée, puis soudain bien réveillé·e la nuit, avec un esprit qui galope à travers conversations, idées, soucis et la to-do de demain, exactement quand tu as le plus besoin qu'il se taise.`,
    `Une partie est purement biologique. Beaucoup de personnes avec un TDAH ont un rythme circadien décalé, ce qui signifie que leur signal de sommeil naturel arrive quelques heures plus tard que ce que le reste du monde attend. À cela s'ajoute que le cerveau TDAH est sous-stimulé quand il n'y a rien à faire, si bien que le calme du coucher peut sembler intolérable plutôt que reposant, et l'esprit part en quête de stimulation sous forme de pensées qui s'emballent ou d'un épisode de plus.`,
    `C'est là qu'intervient le fameux second souffle. Juste au moment où ton corps est enfin prêt à ralentir, une poussée d'énergie ou de concentration surgit, et te voilà à nettoyer la cuisine à fond ou à lancer un projet à minuit. Les chercheurs appellent parfois ce schéma plus large la procrastination du coucher par vengeance : quand la journée ne t'a laissé aucun temps qui te ressemble, la nuit tardive devient la seule fenêtre de liberté – et le sommeil perd en silence.`,
    `Les matins paient alors le prix. Les cerveaux TDAH connaissent souvent une inertie du sommeil intense, cet état lourd et brumeux qui rend le lever presque impossible, peu importe le nombre d'alarmes. Ce n'est pas de la paresse et ce n'est pas une faute morale. C'est le résultat prévisible d'un cerveau qui s'est endormi bien trop tard et qui doit maintenant se réveiller sur un horaire conçu pour l'horloge interne de quelqu'un d'autre.`,
    `Ce qui aide est doux et régulier plutôt que strict. Une routine d'apaisement qui commence plus tôt qu'il ne semble nécessaire, un brain dump sur papier pour vider les pensées qui s'emballent avant le coucher, une lumière plus tamisée le soir et plus vive le matin, et une heure de réveil qui reste à peu près la même même le week-end remettent peu à peu le rythme en place. Externaliser les tâches de demain pour que ton cerveau ait confiance qu'elles sont bien notées fait souvent la différence entre rester éveillé·e et lâcher prise.`,
    `Sois patient·e avec toi-même pendant que tu expérimentes, car le sommeil se répare rarement en une seule nuit. Le but n'est pas une hygiène de sommeil parfaite, comme dans les manuels ; c'est une poignée de petites habitudes répétables qui rendent l'endormissement un peu plus facile et les matins un peu plus doux. Travailler avec ton horloge interne plutôt que contre elle est bien plus durable que forcer un horaire qui n'a jamais été fait pour un cerveau TDAH.`,
  ],
  'body-doubling-adhd': [
    `As-tu déjà remarqué à quel point il est plus facile d'avancer quand quelqu'un d'autre est simplement dans la pièce ? C'est toute l'idée du body doubling, l'une des stratégies de concentration les plus fiables pour les cerveaux TDAH. Un body double est une personne qui travaille à tes côtés – sans aider à ta tâche, juste présente – et sa compagnie tranquille rend la tâche impossible soudain réalisable.`,
    `Cela fonctionne parce que le TDAH est, au fond, un défi d'autorégulation plutôt que de connaissance. En général, tu sais exactement quoi faire ; le plus dur, c'est de commencer et de tenir. Avoir une autre personne là apporte une douce responsabilité externe et un sentiment de concentration emprunté, et cela ajoute juste assez de nouveauté et de légère présence sociale pour donner à ton cerveau le coup de pouce de dopamine dont il a besoin pour démarrer et continuer.`,
    `Le body doubling existe sous de nombreuses formes, tu peux donc choisir ce qui convient à ta vie. Ce peut être une amie qui lit sur le canapé pendant que tu tries des papiers, un partenaire qui cuisine pendant que tu ranges, ou un appel vidéo où deux personnes travaillent en silence sur des choses totalement séparées. Il existe aussi des plateformes de coworking virtuel dédiées et des applis de concentration adaptées au TDAH où tu rejoins une session avec des inconnus et travailles simplement en parallèle.`,
    `La mise en place est étonnamment simple. Décide de ce sur quoi tu vas travailler, dis à ton body double ce que tu commences, mettez-vous d'accord sur une durée, puis démarrez ensemble. Un petit bilan à la fin, où vous nommez ce que chacun a terminé, boucle la boucle et offre une petite dose de satisfaction. L'essentiel, c'est que personne ne te surveille ni ne te juge ; la magie réside uniquement dans la présence partagée.`,
    `Le body doubling brille précisément pour les tâches que les cerveaux TDAH évitent le plus : l'administratif ennuyeux, le ménage, les piles d'e-mails, le remplissage de formulaires, et tout ce qui traîne intact depuis des semaines. Il s'agit moins des compétences de l'autre personne que de briser le sortilège de l'évitement – c'est pourquoi même un compagnon quasi silencieux qui ne connaît rien à ton travail peut transformer complètement ce que tu arrives à faire.`,
    `Si tu as toujours mieux travaillé dans un café animé ou si tu t'es senti·e étrangement productif·ve quand une amie était là, le body doubling transforme simplement cet instinct en un outil que tu peux mobiliser exprès. Ce n'est pas une béquille et ce n'est pas tricher. C'est un aménagement intelligent qui travaille avec le câblage de ton cerveau, et beaucoup en font l'une de leurs façons les plus fiables de commencer.`,
  ],
  'adhd-burnout': [
    `Le burnout TDAH n'est pas la même chose qu'une fatigue ordinaire, ni la même chose que le stress quotidien. C'est l'épuisement profond, de tout le corps, qui arrive après des mois ou des années à pousser un cerveau à fonctionner d'une manière pour laquelle il n'a jamais été fait. Il fait souvent suite à une longue période de masquage, de surcompensation et de serrage de dents au quotidien, jusqu'au jour où les systèmes qui tenaient à peine finissent par lâcher tous d'un coup.`,
    `Les cerveaux TDAH y sont particulièrement vulnérables, parce qu'un effort invisible énorme passe à avoir l'air d'aller bien. Se souvenir, planifier, contenir ses impulsions, gérer ses émotions et répondre aux attentes neurotypiques coûtent tous une énergie exécutive déjà rare. Vivre dans un état constant de rattrapage crée une sorte de découvert exécutif chronique, et un jour la facture tombe sous forme de burnout.`,
    `Les signes se confondent facilement avec autre chose. Des tâches autrefois gérables commencent à sembler impossibles, la motivation disparaît complètement, et même les petites décisions deviennent accablantes. Tu peux te sentir émotionnellement éteint·e ou inhabituellement au bord des larmes, tomber malade plus souvent, te retirer des gens autour de toi, et constater que tes symptômes TDAH – oublis, cécité temporelle, distractibilité – empirent nettement plus que d'habitude.`,
    `Ce qui rend le burnout TDAH si cruel, c'est la honte qui l'accompagne. Beaucoup lisent l'effondrement comme la preuve qu'ils sont paresseux ou défaillants, puis tentent de passer en force avec l'effort même qui l'a provoqué. Cette réaction ne fait que creuser le trou, car le burnout ne se résout pas en faisant plus d'efforts ; il se résout en faisant vraiment, et souvent inconfortablement, moins pendant un temps.`,
    `La récupération commence par la permission de te reposer sans l'avoir mérité. Abaisser la barre volontairement, lâcher chaque engagement non essentiel, externaliser les tâches pour que ton cerveau cesse de les porter, et demander du soutien ne sont pas des caprices ; ce sont le vrai traitement. Il aide aussi de regarder honnêtement ce qui a mené là, car le burnout est souvent le signe que ta vie demande à ta fonction exécutive plus qu'aucun cerveau ne peut donner durablement.`,
    `Guérir d'un burnout TDAH est rarement rapide, et cela arrive plutôt par vagues qu'en ligne droite. Sois patient·e et doux·ce avec toi-même, protège ton énergie comme si elle comptait – parce que c'est le cas –, et reconstruis tes routines lentement, avec bien plus de place pour le repos qu'il ne semble raisonnable. Le but n'est pas de revenir à rouler sur la réserve ; c'est de bâtir une vie qui cesse de vider le réservoir dès le départ.`,
  ],
  'how-to-clean-with-adhd': [
    `Si ton intérieur oscille entre impeccable et chaos total, avec très peu d'entre-deux, tu n'es ni paresseux·se ni négligent·e. Le ménage est vraiment plus difficile pour les cerveaux TDAH, parce qu'il repose précisément sur les compétences que le TDAH complique : démarrer, séquencer, soutenir l'attention et se sentir motivé·e par une tâche sans nouveauté et avec très peu de récompense tant qu'elle n'est pas complètement finie.`,
    `Une grande partie de la difficulté est la pensée tout-ou-rien. Beaucoup de personnes avec un TDAH ont l'impression que le ménage ne compte que si elles font toute la maison parfaitement, si bien que la tâche enfle jusqu'à devenir si énorme que le cerveau refuse de commencer. Le désordre grandit alors jusqu'à devenir une vraie crise, qui génère enfin assez d'urgence et d'adrénaline pour agir – un cycle épuisant et intenable.`,
    `La sortie consiste à rendre le premier pas presque risiblement petit. Au lieu de « nettoyer la cuisine », la tâche devient « dégager une section du plan de travail ». Régler un minuteur sur cinq ou dix minutes seulement fait des merveilles, car cela donne à ton cerveau un point d'arrivée clair et limité, et la pleine permission de t'arrêter quand il sonne. Le plus souvent, commencer est la partie la plus dure, et un peu d'élan te porte plus loin que prévu.`,
    `Emprunter un peu de dopamine rend le tout plus facile. Mettre une playlist préférée, un podcast captivant ou un livre audio transforme une tâche ennuyeuse en quelque chose de supportable, voire d'agréable. Le body doubling aide aussi : nettoyer aux côtés d'une amie, d'un partenaire ou même en appel vidéo te garde ancré·e, et te promettre une petite récompense précise à la fin donne à ton cerveau quelque chose de concret vers quoi avancer.`,
    `Il aide également de viser une remise à zéro plutôt qu'un grand ménage. Ton but, la plupart des jours, est simplement de rendre l'espace à nouveau fonctionnel, pas digne d'un magazine, et « assez bien » est une ligne d'arrivée tout à fait légitime. Garder le matériel de ménage visible et à portée de main, baisser volontairement tes exigences et t'attaquer à une pièce ou même à une seule surface à la fois réduisent tous la friction qui t'empêche de démarrer.`,
    `Le plus important : lâche le poids moral que tu as attaché à un intérieur rangé. Un espace en désordre n'est pas la preuve d'un caractère en désordre ; c'est simplement le signe que les conseils de ménage standards n'ont jamais été conçus pour la façon dont ton cerveau fonctionne. Avec de tout petits pas, un minuteur, un peu de dopamine et beaucoup moins de honte, un intérieur plus apaisé devient bien plus accessible – et un agenda doux qui découpe le travail en petits morceaux peut porter une part surprenante de cette charge pour toi.`,
  ],
}
for (const [slug, paras] of Object.entries(FR_BODY)) {
  articleBody[slug] = { ...(articleBody[slug] || {}), fr: paras }
}
