export const articles = [
  {
    slug: 'why-adhd-brains-struggle-with-planning',
    title: 'Why ADHD Brains Struggle with Planning (And What Actually Helps)',
    excerpt: 'Planning feels impossible — not because you\'re lazy, but because your brain is wired differently. Here\'s the science, and what you can do about it.',
    date: 'June 8, 2026',
    readTime: '6 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '🧠',
  },
  {
    slug: 'dopamine-menu-guide',
    title: 'What Is a Dopamine Menu and How to Make One That Works',
    excerpt: 'A dopamine menu is one of the most effective ADHD tools — and it\'s surprisingly simple. Here\'s how to build yours.',
    date: 'June 8, 2026',
    readTime: '5 min read',
    tag: 'Tools & Tips',
    tagColor: '#FFD6C4',
    tagTextColor: '#E8956A',
    emoji: '🍬',
  },
  {
    slug: 'time-blindness-adhd',
    title: 'Time Blindness: Why You Can\'t Feel Time Passing (And What Helps)',
    excerpt: 'Time blindness is one of the most misunderstood ADHD symptoms. It\'s not about being irresponsible — it\'s neurological.',
    date: 'June 8, 2026',
    readTime: '7 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '⏰',
  },
  {
    slug: 'habit-stacking-adhd',
    title: 'Habit Stacking for ADHD: Building Routines That Actually Stick',
    excerpt: 'Most habit advice fails ADHD brains. Here\'s a gentler approach that works with how your brain actually functions.',
    date: 'June 8, 2026',
    readTime: '5 min read',
    tag: 'Tools & Tips',
    tagColor: '#D4E8D4',
    tagTextColor: '#5BA85B',
    emoji: '🌱',
  },
  {
    slug: 'do-i-have-adhd-test',
    title: 'Do You Have ADHD? How to Know — and What to Do Next',
    excerpt: 'Wondering if you have ADHD? Here are the signs adults actually experience, how the inattentive and hyperactive types differ, and the steps to take if it resonates.',
    date: 'June 11, 2026',
    readTime: '7 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '🧠',
  },
  {
    slug: 'adhd-paralysis',
    title: 'ADHD Paralysis: Why You Freeze — and How to Get Unstuck',
    excerpt: 'You know exactly what to do, you want to do it, and you still can\'t move. That\'s ADHD paralysis. Here\'s why it happens and gentle ways to break the freeze.',
    date: 'June 11, 2026',
    readTime: '6 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '🧊',
  },
  {
    slug: 'best-planner-for-adhd',
    title: 'The Best Planner for ADHD (And Why Most Planners Fail You)',
    excerpt: 'Most planners are built for neurotypical brains, which is why they collect dust by week two. Here\'s what an ADHD-friendly planner actually needs to have.',
    date: 'June 10, 2026',
    readTime: '6 min read',
    tag: 'Tools & Tips',
    tagColor: '#FFD6C4',
    tagTextColor: '#E8956A',
    emoji: '📔',
  },
  {
    slug: 'adhd-in-women',
    title: 'ADHD in Women: The Signs That Get Missed for Years',
    excerpt: 'ADHD in women is chronically underdiagnosed because it often looks like anxiety, perfectionism, or just being "scattered." Here are the signs that get overlooked.',
    date: 'June 10, 2026',
    readTime: '7 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '🌷',
  },
]
