export const articles = [
  {
    slug: 'why-adhd-brains-struggle-with-planning',
    title: 'Why ADHD Brains Struggle with Planning (And What Actually Helps)',
    excerpt: 'Planning feels impossible — not because you\'re lazy, but because your brain is wired differently. Here\'s the science, and what you can do about it.',
    date: 'June 8, 2026',
    readTime: '6 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '🧠',
  },
  {
    slug: 'dopamine-menu-guide',
    title: 'What Is a Dopamine Menu and How to Make One That Works',
    excerpt: 'A dopamine menu is one of the most effective ADHD tools — and it\'s surprisingly simple. Here\'s how to build yours.',
    date: 'June 8, 2026',
    readTime: '5 min read',
    tag: 'Tools & Tips',
    tagColor: '#FFD6C4',
    tagTextColor: '#E8956A',
    emoji: '🍬',
  },
  {
    slug: 'time-blindness-adhd',
    title: 'Time Blindness: Why You Can\'t Feel Time Passing (And What Helps)',
    excerpt: 'Time blindness is one of the most misunderstood ADHD symptoms. It\'s not about being irresponsible — it\'s neurological.',
    date: 'June 8, 2026',
    readTime: '7 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '⏰',
  },
  {
    slug: 'habit-stacking-adhd',
    title: 'Habit Stacking for ADHD: Building Routines That Actually Stick',
    excerpt: 'Most habit advice fails ADHD brains. Here\'s a gentler approach that works with how your brain actually functions.',
    date: 'June 8, 2026',
    readTime: '5 min read',
    tag: 'Tools & Tips',
    tagColor: '#D4E8D4',
    tagTextColor: '#5BA85B',
    emoji: '🌱',
  },
  {
    slug: 'do-i-have-adhd-test',
    title: 'Do You Have ADHD? How to Know — and What to Do Next',
    excerpt: 'Wondering if you have ADHD? Here are the signs adults actually experience, how the inattentive and hyperactive types differ, and the steps to take if it resonates.',
    date: 'June 11, 2026',
    readTime: '7 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '🧠',
  },
  {
    slug: 'adhd-paralysis',
    title: 'ADHD Paralysis: Why You Freeze — and How to Get Unstuck',
    excerpt: 'You know exactly what to do, you want to do it, and you still can\'t move. That\'s ADHD paralysis. Here\'s why it happens and gentle ways to break the freeze.',
    date: 'June 11, 2026',
    readTime: '6 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '🧊',
  },
  {
    slug: 'best-planner-for-adhd',
    title: 'The Best Planner for ADHD (And Why Most Planners Fail You)',
    excerpt: 'Most planners are built for neurotypical brains, which is why they collect dust by week two. Here\'s what an ADHD-friendly planner actually needs to have.',
    date: 'June 10, 2026',
    readTime: '6 min read',
    tag: 'Tools & Tips',
    tagColor: '#FFD6C4',
    tagTextColor: '#E8956A',
    emoji: '📔',
  },
  {
    slug: 'adhd-in-women',
    title: 'ADHD in Women: The Signs That Get Missed for Years',
    excerpt: 'ADHD in women is chronically underdiagnosed because it often looks like anxiety, perfectionism, or just being "scattered." Here are the signs that get overlooked.',
    date: 'June 10, 2026',
    readTime: '7 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '🌷',
  },
  {
    slug: `adhd-rejection-sensitive-dysphoria`,
    title: `ADHD and Rejection Sensitive Dysphoria: Why Criticism Hurts So Much`,
    excerpt: `If one small criticism can ruin your whole day, you're not too sensitive — you might be feeling RSD, one of the most painful and least-known parts of ADHD.`,
    date: `June 12, 2026`,
    readTime: `7 min read`,
    tag: `Understanding ADHD`,
    tagColor: `#E8DEFF`,
    tagTextColor: `#7B5FCC`,
    emoji: `💔`,
  },
  {
    slug: `adhd-and-sleep`,
    title: `ADHD and Sleep: Why Your Brain Won't Switch Off at Night`,
    excerpt: `Racing thoughts at midnight, a second wind right when you should sleep, mornings that feel impossible — ADHD and sleep struggles go hand in hand. Here's why, and what helps.`,
    date: `June 12, 2026`,
    readTime: `7 min read`,
    tag: `Understanding ADHD`,
    tagColor: `#E8DEFF`,
    tagTextColor: `#7B5FCC`,
    emoji: `😴`,
  },
  {
    slug: `body-doubling-adhd`,
    title: `Body Doubling: The ADHD Focus Hack That Actually Works`,
    excerpt: `Why is it so much easier to work when someone else is in the room? Body doubling turns that into a strategy — one of the most reliable ADHD focus tools there is.`,
    date: `June 13, 2026`,
    readTime: `6 min read`,
    tag: `Tools & Tips`,
    tagColor: `#D4E8D4`,
    tagTextColor: `#5BA85B`,
    emoji: `👯`,
  },
  {
    slug: `adhd-burnout`,
    title: `ADHD Burnout: The Signs You're Running on Empty (And How to Recover)`,
    excerpt: `ADHD burnout isn't ordinary tiredness — it's the collapse that comes after months of masking and overcompensating. Here's how to spot it and gently recover.`,
    date: `June 13, 2026`,
    readTime: `7 min read`,
    tag: `Understanding ADHD`,
    tagColor: `#E8DEFF`,
    tagTextColor: `#7B5FCC`,
    emoji: `🔋`,
  },
  {
    slug: `how-to-clean-with-adhd`,
    title: `How to Clean Your House with ADHD Without the Overwhelm`,
    excerpt: `If cleaning feels impossible until it becomes a crisis, you're not lazy — your brain just needs a different approach. Here's how to clean with an ADHD brain, step by gentle step.`,
    date: `June 14, 2026`,
    readTime: `6 min read`,
    tag: `Tools & Tips`,
    tagColor: `#FFD6C4`,
    tagTextColor: `#E8956A`,
    emoji: `🧹`,
  },
  {
    slug: `adhd-emotional-dysregulation`,
    title: `ADHD and Emotional Dysregulation: Why Your Feelings Hit So Hard`,
    excerpt: `When feelings arrive too fast, hit too hard, and last too long — that's not oversensitivity, that's ADHD. Here's the neurology behind it and what actually helps.`,
    date: `June 14, 2026`,
    readTime: `7 min read`,
    tag: `Understanding ADHD`,
    tagColor: `#E8DEFF`,
    tagTextColor: `#7B5FCC`,
    emoji: `🌊`,
  },
  {
    slug: `adhd-hyperfocus`,
    title: `ADHD Hyperfocus: Why Your Brain Sometimes Can't Stop`,
    excerpt: `Hyperfocus is the paradoxical flip side of ADHD distractibility — hours of involuntary absorption you can't control. Here's why it happens and how to work with it.`,
    date: `June 14, 2026`,
    readTime: `7 min read`,
    tag: `Understanding ADHD`,
    tagColor: `#E8DEFF`,
    tagTextColor: `#7B5FCC`,
    emoji: `🔬`,
  },
  {
    slug: `adhd-executive-dysfunction`,
    title: `ADHD Executive Dysfunction: Why Simple Tasks Feel Impossible`,
    excerpt: `Executive dysfunction is the core of ADHD — not laziness, not bad will. Here's what happens in the brain and why some days are so much harder than others.`,
    date: `June 14, 2026`,
    readTime: `8 min read`,
    tag: `Understanding ADHD`,
    tagColor: `#E8DEFF`,
    tagTextColor: `#7B5FCC`,
    emoji: `🧠`,
  },
  {
    slug: `adhd-and-anxiety`,
    title: `ADHD and Anxiety: Why They So Often Go Together`,
    excerpt: `ADHD and anxiety disorders co-occur in roughly half of adults with ADHD — but why? Here's the neurological link and how to tell what's causing what.`,
    date: `June 14, 2026`,
    readTime: `7 min read`,
    tag: `Understanding ADHD`,
    tagColor: `#E8DEFF`,
    tagTextColor: `#7B5FCC`,
    emoji: `💙`,
  },
  {
    slug: `adhd-sensory-sensitivity`,
    title: `ADHD and Sensory Sensitivity: When the World Is Too Loud, Too Bright, Too Much`,
    excerpt: `Many people with ADHD are extraordinarily sensitive to sounds, light, textures or crowds. It's not drama — it's neurology. Here's what's behind it.`,
    date: `June 14, 2026`,
    readTime: `7 min read`,
    tag: `Understanding ADHD`,
    tagColor: `#E8DEFF`,
    tagTextColor: `#7B5FCC`,
    emoji: `✨`,
  },
  {
    slug: `adhd-tax`,
    title: `The ADHD Tax: The Hidden Cost of Having Your Brain`,
    excerpt: `Late fees, forgotten subscriptions, replacing things you already own. The ADHD tax is real, it's expensive — and it's not a character flaw.`,
    date: 'July 6, 2026',
    readTime: '6 min read',
    tag: 'Tools & Tips',
    tagColor: '#FFD6C4',
    tagTextColor: '#C07A3E',
    emoji: '💸',
  },
  {
    slug: `adhd-waiting-mode`,
    title: `Waiting Mode: Why You Can't Do Anything Before a 3 PM Appointment`,
    excerpt: `One appointment in the afternoon, and the entire day is gone. If this sounds familiar, you're experiencing waiting mode — and no, you're not being dramatic.`,
    date: 'July 6, 2026',
    readTime: '5 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '⏳',
  },
  {
    slug: `adhd-doom-piles`,
    title: `Doom Piles: Why Your Clutter Isn't Laziness`,
    excerpt: `That pile of stuff on the chair. The box of random things. The bag you haven't unpacked. Doom piles have a logic — and once you see it, you can work with it.`,
    date: 'July 6, 2026',
    readTime: '5 min read',
    tag: 'Tools & Tips',
    tagColor: '#FFD6C4',
    tagTextColor: '#C07A3E',
    emoji: '📦',
  },
  {
    slug: `adhd-object-permanence`,
    title: `Out of Sight, Gone Forever: ADHD and Object Permanence`,
    excerpt: `Food forgotten in the fridge. Friends you love but never text. Projects that vanish the moment you close the tab. Here's why — and what helps.`,
    date: 'July 6, 2026',
    readTime: '5 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '🫥',
  },
  {
    slug: `adhd-texting`,
    title: `Why Replying to Texts Feels Impossible (You're Not a Bad Friend)`,
    excerpt: `You read the message. You meant to reply. It's been eleven days. The ADHD texting spiral, explained with zero judgment.`,
    date: 'July 6, 2026',
    readTime: '5 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '📱',
  },
  {
    slug: `gifted-kid-adhd`,
    title: `From "Gifted Kid" to Burnt-Out Adult: The ADHD Pipeline Nobody Warned You About`,
    excerpt: `School was easy, so nobody looked closer. Then life stopped being a classroom — and everything fell apart. This story is more common than you think.`,
    date: 'July 6, 2026',
    readTime: '6 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '🎓',
  },
  {
    slug: `adhd-masking`,
    title: `ADHD Masking: The Exhausting Performance of Being Fine`,
    excerpt: `Smiling through the chaos, mimicking "normal," apologizing constantly. Masking works — until the bill arrives. Here's what it costs and how to put it down.`,
    date: 'July 6, 2026',
    readTime: '6 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '🎭',
  },
  {
    slug: `revenge-bedtime-procrastination`,
    title: `Revenge Bedtime Procrastination: Why You Won't Go to Sleep`,
    excerpt: `You're exhausted. You know tomorrow will hurt. And yet at 1 AM you're still scrolling — on purpose. There's a reason, and it's not lack of discipline.`,
    date: 'July 6, 2026',
    readTime: '5 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '🌙',
  },
  {
    slug: `adhd-transitions`,
    title: `Why You Can't Start, Stop, or Leave the House: ADHD and Transitions`,
    excerpt: `The shower you avoided for hours and then didn't want to leave. The game you can't quit. The door you can't walk out of. It's all the same thing.`,
    date: 'July 6, 2026',
    readTime: '6 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '🚪',
  },
  {
    slug: `adhd-hobby-graveyard`,
    title: `The Hobby Graveyard: Why You Abandon Everything You Once Loved`,
    excerpt: `The guitar. The yarn. The roller skates. The language app. You weren't flaky — your brain was doing exactly what it's built to do. A kinder way to look at the graveyard.`,
    date: 'July 6, 2026',
    readTime: '5 min read',
    tag: 'Understanding ADHD',
    tagColor: '#E8DEFF',
    tagTextColor: '#7B5FCC',
    emoji: '🎨',
  },
  {
    slug: `adhd-and-food`,
    title: `Forgetting to Eat, Then Eating Everything: ADHD and Food`,
    excerpt: `Skipping meals without noticing, then inhaling snacks at midnight. Eating the same meal for weeks. Cooking feeling impossible. None of this is a willpower problem.`,
    date: 'July 6, 2026',
    readTime: '6 min read',
    tag: 'Tools & Tips',
    tagColor: '#FFD6C4',
    tagTextColor: '#C07A3E',
    emoji: '🍜',
  },
  {
    slug: `adhd-decision-fatigue`,
    title: `Why Choosing What to Watch Takes an Hour: ADHD and Decision Fatigue`,
    excerpt: `Forty minutes of scrolling the menu, then you rewatch the same show anyway. Decisions drain ADHD brains faster — here's how to spend fewer of them.`,
    date: 'July 6, 2026',
    readTime: '5 min read',
    tag: 'Tools & Tips',
    tagColor: '#FFD6C4',
    tagTextColor: '#C07A3E',
    emoji: '🤯',
  },
]

export type Article = (typeof articles)[number]

/**
 * Related articles for the bottom of an article page.
 *
 * Same-tag articles first, topped up from the other tags when a tag has fewer
 * than `count` siblings.
 *
 * Within each pool the starting point rotates by the article's position *within
 * its own tag* (not its index in the full list, which bunches up once the list
 * is filtered). That keeps the even inbound-link distribution the previous
 * index-adjacency logic was built for — every article is currently linked from
 * exactly three others, no orphans — while making the picks topical.
 */
export function relatedArticles(slug: string, count = 3): Article[] {
  const current = articles.find(a => a.slug === slug)
  if (!current) return []

  const tagPeers = articles.filter(a => a.tag === current.tag)
  const posInTag = tagPeers.findIndex(a => a.slug === slug)

  const sameTag = tagPeers.filter(a => a.slug !== slug)
  const otherTags = articles.filter(a => a.slug !== slug && a.tag !== current.tag)

  const picked: Article[] = []
  for (const pool of [sameTag, otherTags]) {
    if (picked.length >= count || pool.length === 0) continue
    const start = posInTag % pool.length
    for (let i = 0; i < pool.length && picked.length < count; i++) {
      picked.push(pool[(start + i) % pool.length])
    }
  }
  return picked.slice(0, count)
}
